import { getRepository } from 'typeorm';
import fm_municipio from '../models/fm_municipio';

const municipio = async (): Promise<void> => {
	const data: fm_municipio[] = [
		{ id: 1, municipio: 'LIBERTADOR', id_estado: 1 },
		{ id: 2, municipio: 'AUTONOMO ALTO ORINOCO', id_estado: 2 },
		{ id: 3, municipio: 'AUTONOMO ATABAPO', id_estado: 2 },
		{ id: 4, municipio: 'AUTONOMO ATURES', id_estado: 2 },
		{ id: 5, municipio: 'AUTONOMO AUTANA', id_estado: 2 },
		{ id: 6, municipio: 'AUTONOMO MAROA', id_estado: 2 },
		{ id: 7, municipio: 'AUTONOMO MANAPIARE', id_estado: 2 },
		{ id: 8, municipio: 'AUTONOMO RIO NEGRO', id_estado: 2 },
		{ id: 9, municipio: 'ANACO', id_estado: 3 },
		{ id: 10, municipio: 'ARAGUA', id_estado: 3 },
		{ id: 11, municipio: 'FERNANDO DE PEÑA', id_estado: 2 },
		{ id: 12, municipio: 'FRANCISCO DEL CARMEN CARVAJAL', id_estado: 3 },
		{ id: 13, municipio: 'FRANCISCO DE MIRANDA', id_estado: 3 },
		{ id: 14, municipio: 'GUANTA', id_estado: 3 },
		{ id: 15, municipio: 'INDEPENDENCIA', id_estado: 3 },
		{ id: 16, municipio: 'JUAN ANTONIO SOTILLO', id_estado: 3 },
		{ id: 17, municipio: 'JUAN MANUEL CAJIGAL', id_estado: 3 },
		{ id: 18, municipio: 'JOSE GREGORIO MONAGAS', id_estado: 3 },
		{ id: 19, municipio: 'LIBERTAD', id_estado: 3 },
		{ id: 20, municipio: 'MANUEL EZEQUIEL BRUZUAL', id_estado: 3 },
		{ id: 21, municipio: 'PEDRO MARIA FREITES', id_estado: 3 },
		{ id: 22, municipio: 'PIRITU', id_estado: 3 },
		{ id: 23, municipio: 'SAN JOSE DE GUANIPA', id_estado: 3 },
		{ id: 24, municipio: 'SAN JUAN DE CAPISTRANO', id_estado: 3 },
		{ id: 25, municipio: 'SANTA ANA', id_estado: 3 },
		{ id: 26, municipio: 'SIMON BOLIVAR', id_estado: 3 },
		{ id: 27, municipio: 'SIMON RODRIGUEZ', id_estado: 3 },
		{ id: 28, municipio: 'SIR ARTHUR MC GREGOR', id_estado: 3 },
		{ id: 29, municipio: 'TURIST DIEGO BAUTISTA URBANEJA', id_estado: 3 },
		{ id: 30, municipio: 'ACHAGUAS', id_estado: 4 },
		{ id: 31, municipio: 'BIRUACA', id_estado: 4 },
		{ id: 32, municipio: 'MUÑÓS', id_estado: 4 },
		{ id: 33, municipio: 'PAEZ', id_estado: 4 },
		{ id: 34, municipio: 'PEDRO CAMEJO', id_estado: 4 },
		{ id: 35, municipio: 'ROMULO GALLEGOS', id_estado: 4 },
		{ id: 36, municipio: 'SAN FERNANDO', id_estado: 4 },
		{ id: 37, municipio: 'BOLIVAR', id_estado: 5 },
		{ id: 38, municipio: 'JOSE GREGORIO MONAGAS', id_estado: 5 },
		{ id: 39, municipio: 'GIRARDOT', id_estado: 5 },
		{ id: 40, municipio: 'JOSE ANGEL LAMAS', id_estado: 5 },
		{ id: 41, municipio: 'JOSE FELIX RIBAS', id_estado: 5 },
		{ id: 42, municipio: 'JOSE RAFAEL REVENGA', id_estado: 5 },
		{ id: 43, municipio: 'LIBERTADOR', id_estado: 5 },
		{ id: 44, municipio: 'MARIO BRICEÑÓ', id_estado: 5 },
		{ id: 45, municipio: 'SAN CASIMIRO', id_estado: 5 },
		{ id: 46, municipio: 'SAN SEBASTIAN', id_estado: 5 },
		{ id: 47, municipio: 'SANTIAGO MARIÑÓ', id_estado: 5 },
		{ id: 48, municipio: 'SANTOS MICHELENA', id_estado: 5 },
		{ id: 49, municipio: 'SUCRE', id_estado: 5 },
		{ id: 50, municipio: 'TOVAR', id_estado: 5 },
		{ id: 51, municipio: 'URDANETA', id_estado: 5 },
		{ id: 52, municipio: 'ZAMORA', id_estado: 5 },
		{ id: 53, municipio: 'FRANCISCO LINARES ALCANTARA', id_estado: 5 },
		{ id: 54, municipio: 'OCUMARE DE LA COSTA DE ORO', id_estado: 5 },
		{ id: 55, municipio: 'ALBERTO ARVELO TORREALBA', id_estado: 6 },
		{ id: 56, municipio: 'ANTONIO JOSE DE SUCRE', id_estado: 6 },
		{ id: 57, municipio: 'ARISMENDI', id_estado: 6 },
		{ id: 58, municipio: 'BARINAS', id_estado: 6 },
		{ id: 59, municipio: 'BOLIVAR', id_estado: 6 },
		{ id: 60, municipio: 'CRUZ PAREDES', id_estado: 6 },
		{ id: 61, municipio: 'EZEQUIEL ZAMORA', id_estado: 6 },
		{ id: 62, municipio: 'OBISPOS', id_estado: 6 },
		{ id: 63, municipio: 'PEDRAZA', id_estado: 6 },
		{ id: 64, municipio: 'ROJAS', id_estado: 6 },
		{ id: 65, municipio: 'SOSA', id_estado: 6 },
		{ id: 66, municipio: 'ANDRES ELOY BLANCO', id_estado: 6 },
		{ id: 67, municipio: 'CARONI', id_estado: 15 },
		{ id: 68, municipio: 'CEDEÑÓ', id_estado: 15 },
		{ id: 69, municipio: 'EL CALLAO', id_estado: 15 },
		{ id: 70, municipio: 'GRAN SABANA', id_estado: 15 },
		{ id: 71, municipio: 'HERES', id_estado: 15 },
		{ id: 72, municipio: 'PIAR', id_estado: 15 },
		{ id: 73, municipio: 'RAUL LEONI', id_estado: 15 },
		{ id: 74, municipio: 'ROSCIO', id_estado: 15 },
		{ id: 75, municipio: 'SIFONTES', id_estado: 15 },
		{ id: 76, municipio: 'SUCRE', id_estado: 15 },
		{ id: 77, municipio: 'PADRE PEDRO CHIEN', id_estado: 15 },
		{ id: 78, municipio: 'BEJUMA', id_estado: 8 },
		{ id: 79, municipio: 'BOLIVAR', id_estado: 8 },
		{ id: 80, municipio: 'DIEGO IBARRA', id_estado: 8 },
		{ id: 81, municipio: 'GUACARA', id_estado: 8 },
		{ id: 82, municipio: 'JUAN JOSE MORA', id_estado: 8 },
		{ id: 83, municipio: 'LIBERTADOR', id_estado: 8 },
		{ id: 84, municipio: 'LOS GUAYOS', id_estado: 8 },
		{ id: 85, municipio: 'MIRANDA', id_estado: 8 },
		{ id: 86, municipio: 'MONTALBAN', id_estado: 8 },
		{ id: 87, municipio: 'NAGUANAGUA', id_estado: 8 },
		{ id: 88, municipio: 'PUERTO CABELLO', id_estado: 8 },
		{ id: 89, municipio: 'SAN DIEGO', id_estado: 8 },
		{ id: 90, municipio: 'SAN JOAQUIN', id_estado: 8 },
		{ id: 91, municipio: 'VALENCIA', id_estado: 8 },
		{ id: 92, municipio: 'ANZOATEGUI', id_estado: 9 },
		{ id: 93, municipio: 'RAUL LEONI', id_estado: 9 },
		{ id: 94, municipio: 'GIRARDOT', id_estado: 9 },
		{ id: 95, municipio: 'LIMA BLANCO', id_estado: 9 },
		{ id: 96, municipio: 'PAO DE SAN JUAN BAUTISTA', id_estado: 9 },
		{ id: 97, municipio: 'RICAURTE', id_estado: 9 },
		{ id: 98, municipio: 'ROMULO GALLEGOS', id_estado: 9 },
		{ id: 99, municipio: 'SAN CARLOS', id_estado: 9 },
		{ id: 100, municipio: 'TINACO', id_estado: 9 },
		{ id: 101, municipio: 'ANTONIO DIAZ', id_estado: 10 },
		{ id: 102, municipio: 'CASACOIMA', id_estado: 10 },
		{ id: 103, municipio: 'PEDERNALES', id_estado: 10 },
		{ id: 104, municipio: 'TUCUPITA', id_estado: 10 },
		{ id: 105, municipio: 'ACOSTA', id_estado: 11 },
		{ id: 106, municipio: 'BOLIVAR', id_estado: 11 },
		{ id: 107, municipio: 'BUCHIVACOA', id_estado: 11 },
		{ id: 108, municipio: 'CACIQUE MANAURE', id_estado: 11 },
		{ id: 109, municipio: 'CARIRUBANA', id_estado: 11 },
		{ id: 110, municipio: 'COLINA', id_estado: 11 },
		{ id: 111, municipio: 'DABAJURO', id_estado: 11 },
		{ id: 112, municipio: 'DEMOCRACIA', id_estado: 11 },
		{ id: 113, municipio: 'FALCON', id_estado: 11 },
		{ id: 114, municipio: 'FEDERACION', id_estado: 11 },
		{ id: 115, municipio: 'JACURA', id_estado: 11 },
		{ id: 116, municipio: 'LOS TAQUES', id_estado: 11 },
		{ id: 117, municipio: 'MAUROA', id_estado: 11 },
		{ id: 118, municipio: 'ROMULO GALLEGOS', id_estado: 11 },
		{ id: 119, municipio: 'MONSEÑOR', id_estado: 11 },
		{ id: 120, municipio: 'PALMASOLA', id_estado: 11 },
		{ id: 121, municipio: 'PETIT', id_estado: 11 },
		{ id: 122, municipio: 'PIRITU', id_estado: 11 },
		{ id: 123, municipio: 'SAN FRANCISCO', id_estado: 11 },
		{ id: 124, municipio: 'SILVA', id_estado: 11 },
		{ id: 125, municipio: 'SUCRE', id_estado: 11 },
		{ id: 126, municipio: 'TOCOPERO', id_estado: 11 },
		{ id: 127, municipio: 'UNION', id_estado: 11 },
		{ id: 128, municipio: 'URUMACO', id_estado: 11 },
		{ id: 129, municipio: 'ZAMORA', id_estado: 11 },
		{ id: 130, municipio: 'CAMAGUAN', id_estado: 12 },
		{ id: 131, municipio: 'CHAGUARAMAS', id_estado: 12 },
		{ id: 132, municipio: 'EL SOCORRO', id_estado: 12 },
		{ id: 133, municipio: 'SAN GERONIMO DE GUAYABAL', id_estado: 12 },
		{ id: 134, municipio: 'FEDERACION', id_estado: 12 },
		{ id: 135, municipio: 'LAS MERCEDES', id_estado: 12 },
		{ id: 136, municipio: 'JULIAN MELLADO', id_estado: 12 },
		{ id: 137, municipio: 'FRANCISCO DE MIRANDA', id_estado: 12 },
		{ id: 138, municipio: 'JOSE TADEO MONAGAS', id_estado: 12 },
		{ id: 139, municipio: 'ORTIZ', id_estado: 12 },
		{ id: 140, municipio: 'JOSE FELIX RIBAS', id_estado: 12 },
		{ id: 141, municipio: 'JUAN GERMAN ROSCIO', id_estado: 12 },
		{ id: 142, municipio: 'SAN JOSE DE GUARIBE', id_estado: 12 },
		{ id: 143, municipio: 'SANTA MARIA DE IPIRE', id_estado: 12 },
		{ id: 144, municipio: 'PEDRO ZARAZA', id_estado: 12 },
		{ id: 145, municipio: 'ANDRES ELOY BLANCO', id_estado: 13 },
		{ id: 146, municipio: 'CRESPO', id_estado: 13 },
		{ id: 147, municipio: 'IRIBARREN', id_estado: 13 },
		{ id: 148, municipio: 'JIMENEZ', id_estado: 13 },
		{ id: 149, municipio: 'MORAN', id_estado: 13 },
		{ id: 150, municipio: 'PALAVECINO', id_estado: 13 },
		{ id: 151, municipio: 'SIMON PLANAS', id_estado: 13 },
		{ id: 152, municipio: 'TORRES', id_estado: 13 },
		{ id: 153, municipio: 'URDANETA', id_estado: 13 },
		{ id: 154, municipio: 'ALBERTO ADRIANI', id_estado: 14 },
		{ id: 155, municipio: 'ANDRES BELLO', id_estado: 14 },
		{ id: 156, municipio: 'ANTONIO PINTO SALINAS', id_estado: 14 },
		{ id: 157, municipio: 'ARICAGUA', id_estado: 14 },
		{ id: 158, municipio: 'ARZOBISPO CHACON', id_estado: 14 },
		{ id: 159, municipio: 'CAMPO ELIAS', id_estado: 14 },
		{ id: 160, municipio: 'JOSE FELIX RIBAS', id_estado: 14 },
		{ id: 161, municipio: 'CARDENAL QUINTERO', id_estado: 14 },
		{ id: 162, municipio: 'GUARAQUE', id_estado: 14 },
		{ id: 163, municipio: 'JULIO CESAR SALAS', id_estado: 14 },
		{ id: 164, municipio: 'JUSTO BRICEÑÓ', id_estado: 14 },
		{ id: 165, municipio: 'LIBERTADOR', id_estado: 14 },
		{ id: 166, municipio: 'MIRANDA', id_estado: 14 },
		{ id: 167, municipio: 'OBISPO RAMOS DE LORA', id_estado: 14 },
		{ id: 168, municipio: 'PADRE NOGUERA', id_estado: 14 },
		{ id: 169, municipio: 'PUEBLO LLANO', id_estado: 14 },
		{ id: 170, municipio: 'RANGEL', id_estado: 14 },
		{ id: 171, municipio: 'RIVAS DAVILA', id_estado: 14 },
		{ id: 172, municipio: 'SANTOS MARQUINA', id_estado: 14 },
		{ id: 173, municipio: 'SUCRE', id_estado: 14 },
		{ id: 174, municipio: 'TOVAR', id_estado: 14 },
		{ id: 175, municipio: 'TULIO FEBRES CORDERO', id_estado: 14 },
		{ id: 176, municipio: 'ZEA', id_estado: 14 },
		{ id: 177, municipio: 'ACEVEDO', id_estado: 7 },
		{ id: 178, municipio: 'ANDRES BELLO', id_estado: 7 },
		{ id: 179, municipio: 'CAMPO ELIAS', id_estado: 3 },
		{ id: 180, municipio: 'BRION', id_estado: 7 },
		{ id: 181, municipio: 'BUROZ', id_estado: 7 },
		{ id: 182, municipio: 'CARRIZAL', id_estado: 7 },
		{ id: 183, municipio: 'CHACAO', id_estado: 7 },
		{ id: 184, municipio: 'CRISTOBAL ROJAS', id_estado: 7 },
		{ id: 185, municipio: 'EL HATILLO', id_estado: 7 },
		{ id: 186, municipio: 'GUAICAIPURO', id_estado: 7 },
		{ id: 187, municipio: 'INDEPENDENCIA', id_estado: 7 },
		{ id: 188, municipio: 'TOMAS LANDER', id_estado: 7 },
		{ id: 189, municipio: 'LOS SALIAS', id_estado: 7 },
		{ id: 190, municipio: 'PAEZ', id_estado: 7 },
		{ id: 191, municipio: 'PAZ CASTILLO', id_estado: 7 },
		{ id: 192, municipio: 'PEDRO GUAL', id_estado: 7 },
		{ id: 193, municipio: 'PLAZA', id_estado: 7 },
		{ id: 194, municipio: 'SIMON BOLIVAR', id_estado: 7 },
		{ id: 195, municipio: 'SUCRE', id_estado: 7 },
		{ id: 196, municipio: 'URDANETA', id_estado: 7 },
		{ id: 197, municipio: 'ZAMORA', id_estado: 7 },
		{ id: 198, municipio: 'ACOSTA', id_estado: 16 },
		{ id: 199, municipio: 'AGUASAY', id_estado: 16 },
		{ id: 200, municipio: 'BRION', id_estado: 16 },
		{ id: 201, municipio: 'CARIPE', id_estado: 16 },
		{ id: 202, municipio: 'CEDEÑO', id_estado: 16 },
		{ id: 203, municipio: 'EZEQUIEL ZAMORA', id_estado: 16 },
		{ id: 204, municipio: 'LIBERTADOR', id_estado: 16 },
		{ id: 205, municipio: 'MATURIN', id_estado: 16 },
		{ id: 206, municipio: 'PIAR', id_estado: 16 },
		{ id: 207, municipio: 'PUNCERES', id_estado: 16 },
		{ id: 208, municipio: 'SANTA BARBARA', id_estado: 16 },
		{ id: 209, municipio: 'SOTILLO', id_estado: 16 },
		{ id: 210, municipio: 'URACOA', id_estado: 16 },
		{ id: 211, municipio: 'ANTOLIN DEL CAMPO', id_estado: 17 },
		{ id: 212, municipio: 'ARISMENDI', id_estado: 17 },
		{ id: 213, municipio: 'DIAZ', id_estado: 17 },
		{ id: 214, municipio: 'SIMON BOLIVAR', id_estado: 17 },
		{ id: 215, municipio: 'GOMEZ', id_estado: 17 },
		{ id: 216, municipio: 'MANEIRO', id_estado: 17 },
		{ id: 217, municipio: 'MARCANO', id_estado: 17 },
		{ id: 218, municipio: 'MARIÑO', id_estado: 17 },
		{ id: 219, municipio: 'PENINSULA DE MACANAO', id_estado: 17 },
		{ id: 220, municipio: 'TUBORES', id_estado: 17 },
		{ id: 221, municipio: 'VILLALBA', id_estado: 17 },
		{ id: 222, municipio: 'AGUA BLANCA', id_estado: 18 },
		{ id: 223, municipio: 'ARAURE', id_estado: 18 },
		{ id: 224, municipio: 'ESTELLER', id_estado: 18 },
		{ id: 225, municipio: 'GUANARE', id_estado: 18 },
		{ id: 226, municipio: 'GUANARITO', id_estado: 18 },
		{ id: 227, municipio: 'MONSEÑOR', id_estado: 18 },
		{ id: 228, municipio: 'OSPINO', id_estado: 18 },
		{ id: 229, municipio: 'PAEZ', id_estado: 18 },
		{ id: 230, municipio: 'PAPELON', id_estado: 18 },
		{ id: 231, municipio: 'SAN GENARO DE BOCONOITO', id_estado: 18 },
		{ id: 232, municipio: 'SAN RAFAEL DE ONOTO', id_estado: 18 },
		{ id: 233, municipio: 'SANTA ROSALIA', id_estado: 18 },
		{ id: 234, municipio: 'SUCRE', id_estado: 18 },
		{ id: 235, municipio: 'TUREN', id_estado: 18 },
		{ id: 236, municipio: 'ANDRES ELOY BLANCO', id_estado: 19 },
		{ id: 237, municipio: 'ANDRES MATA', id_estado: 19 },
		{ id: 238, municipio: 'ARISMENDI', id_estado: 19 },
		{ id: 239, municipio: 'PENINSULA DE MACANAO', id_estado: 19 },
		{ id: 240, municipio: 'BERMUDEZ', id_estado: 19 },
		{ id: 241, municipio: 'BOLIVAR', id_estado: 19 },
		{ id: 242, municipio: 'CAJIGAL', id_estado: 19 },
		{ id: 243, municipio: 'CRUZ SALMERON ACOSTA', id_estado: 19 },
		{ id: 244, municipio: 'LIBERTADOR', id_estado: 19 },
		{ id: 245, municipio: 'MARIÑO', id_estado: 19 },
		{ id: 246, municipio: 'MEJIA', id_estado: 19 },
		{ id: 247, municipio: 'MONTES', id_estado: 19 },
		{ id: 248, municipio: 'RIBERO', id_estado: 19 },
		{ id: 249, municipio: 'SUCRE', id_estado: 19 },
		{ id: 250, municipio: 'VALDEZ', id_estado: 19 },
		{ id: 251, municipio: 'ANDRES BELLO', id_estado: 20 },
		{ id: 252, municipio: 'ANTONIO ROMULO COSTA', id_estado: 20 },
		{ id: 253, municipio: 'AYACUCHO', id_estado: 20 },
		{ id: 254, municipio: 'BOLIVAR', id_estado: 20 },
		{ id: 255, municipio: 'CARDENAS', id_estado: 20 },
		{ id: 256, municipio: 'CORDOBA', id_estado: 20 },
		{ id: 257, municipio: 'FERNANDEZ FEO', id_estado: 20 },
		{ id: 258, municipio: 'FRANCISCO DE MIRANDA', id_estado: 20 },
		{ id: 259, municipio: 'GARCIA DE HEVIA', id_estado: 20 },
		{ id: 260, municipio: 'BERMUDEZ', id_estado: 20 },
		{ id: 261, municipio: 'INDEPENDENCIA', id_estado: 20 },
		{ id: 262, municipio: 'JAUREGUI', id_estado: 20 },
		{ id: 263, municipio: 'JOSE MARIA VARGAS', id_estado: 20 },
		{ id: 264, municipio: 'JUNIN', id_estado: 20 },
		{ id: 265, municipio: 'LIBERTAD', id_estado: 20 },
		{ id: 266, municipio: 'LIBERTADOR', id_estado: 20 },
		{ id: 267, municipio: 'LOBATERA', id_estado: 20 },
		{ id: 268, municipio: 'MICHELENA', id_estado: 20 },
		{ id: 269, municipio: 'PANAMERICANO', id_estado: 20 },
		{ id: 270, municipio: 'PEDRO MARÍA UREÑA', id_estado: 20 },
		{ id: 271, municipio: 'RAFAEL URDANETA', id_estado: 20 },
		{ id: 272, municipio: 'SAMUEL DARIO MALDONADO', id_estado: 20 },
		{ id: 273, municipio: 'SAN CRISTOBAL', id_estado: 20 },
		{ id: 274, municipio: 'SEBORUCO', id_estado: 20 },
		{ id: 275, municipio: 'SIMON RODRIGUEZ', id_estado: 20 },
		{ id: 276, municipio: 'SUCRE', id_estado: 20 },
		{ id: 277, municipio: 'TORBES', id_estado: 20 },
		{ id: 278, municipio: 'URIBANTE', id_estado: 20 },
		{ id: 279, municipio: 'GUASIMO', id_estado: 20 },
		{ id: 280, municipio: 'ANDRES BELLO', id_estado: 21 },
		{ id: 281, municipio: 'BOCONO', id_estado: 21 },
		{ id: 282, municipio: 'BOLIVAR', id_estado: 21 },
		{ id: 283, municipio: 'CANDELARIA', id_estado: 21 },
		{ id: 284, municipio: 'CARACHE', id_estado: 21 },
		{ id: 285, municipio: 'ESCUQUE', id_estado: 21 },
		{ id: 286, municipio: 'JOSE FELIPE MARQUEZ CAÑOZALES', id_estado: 21 },
		{ id: 287, municipio: 'JUAN VICENTE CAMPO ELIAS', id_estado: 21 },
		{ id: 288, municipio: 'LA CEIBA', id_estado: 21 },
		{ id: 289, municipio: 'MIRANDA', id_estado: 21 },
		{ id: 290, municipio: 'MONTE CARMELO', id_estado: 21 },
		{ id: 291, municipio: 'MOTATAN', id_estado: 21 },
		{ id: 292, municipio: 'PAMPAN', id_estado: 21 },
		{ id: 293, municipio: 'PAMPANITO', id_estado: 21 },
		{ id: 294, municipio: 'RAFAEL RANGEL', id_estado: 21 },
		{ id: 295, municipio: 'SAN RAFAEL DE CARVAJAL', id_estado: 21 },
		{ id: 296, municipio: 'SUCRE', id_estado: 21 },
		{ id: 297, municipio: 'TRUJILLO', id_estado: 21 },
		{ id: 298, municipio: 'URDANETA', id_estado: 21 },
		{ id: 299, municipio: 'VALERA', id_estado: 21 },
		{ id: 300, municipio: 'ANDRES BELLO', id_estado: 22 },
		{ id: 301, municipio: 'BOLIVAR', id_estado: 22 },
		{ id: 302, municipio: 'BRUZUAL', id_estado: 22 },
		{ id: 303, municipio: 'COCOROTE', id_estado: 22 },
		{ id: 304, municipio: 'INDEPENDENCIA', id_estado: 22 },
		{ id: 305, municipio: 'JOSE ANTONIO PAEZ', id_estado: 22 },
		{ id: 306, municipio: 'LA TRINIDAD', id_estado: 22 },
		{ id: 307, municipio: 'MANUEL MONGE', id_estado: 22 },
		{ id: 308, municipio: 'NIRGUA', id_estado: 22 },
		{ id: 309, municipio: 'PEÑA', id_estado: 22 },
		{ id: 310, municipio: 'SAN FELIPE', id_estado: 22 },
		{ id: 311, municipio: 'SUCRE', id_estado: 22 },
		{ id: 312, municipio: 'PAMPAN', id_estado: 22 },
		{ id: 313, municipio: 'VEROES', id_estado: 22 },
		{ id: 314, municipio: 'ALMIRANTE PADILLA', id_estado: 23 },
		{ id: 315, municipio: 'BARALT', id_estado: 23 },
		{ id: 316, municipio: 'CABIMAS', id_estado: 23 },
		{ id: 317, municipio: 'CATATUMBO', id_estado: 23 },
		{ id: 318, municipio: 'COLON', id_estado: 23 },
		{ id: 319, municipio: 'FRANCISCO JAVIER PULGAR', id_estado: 23 },
		{ id: 320, municipio: 'JESUS ENRIQUE LOZADA', id_estado: 23 },
		{ id: 321, municipio: 'JESUS MARIA SEMPRUN', id_estado: 23 },
		{ id: 322, municipio: 'LA CAÑADA URDANETA', id_estado: 23 },
		{ id: 323, municipio: 'LAGUNILLAS', id_estado: 23 },
		{ id: 324, municipio: 'MACHIQUES DE PERIJA', id_estado: 23 },
		{ id: 325, municipio: 'MARA', id_estado: 23 },
		{ id: 326, municipio: 'MARACAIBO', id_estado: 23 },
		{ id: 327, municipio: 'MIRANDA', id_estado: 23 },
		{ id: 328, municipio: 'PAEZ', id_estado: 23 },
		{ id: 329, municipio: 'ROSARIO DE PERIJA', id_estado: 23 },
		{ id: 330, municipio: 'SAN FRANCISCO', id_estado: 23 },
		{ id: 331, municipio: 'SANTA RITA', id_estado: 23 },
		{ id: 332, municipio: 'SIMON BOLIVAR', id_estado: 23 },
		{ id: 333, municipio: 'SUCRE', id_estado: 23 },
		{ id: 334, municipio: 'VALMORE RODRIGUEZ', id_estado: 23 },
		{ id: 335, municipio: 'VARGAS', id_estado: 24 },
		{ id: 336, municipio: 'DEPENDENCIAS FEDERALES', id_estado: 25 },
		{ id: 337, municipio: 'BARUTA', id_estado: 7 },
		{ id: 338, municipio: 'CARACILO PARRA Y OLMEDO', id_estado: 14 },
		{ id: 339, municipio: 'LEONARDO INFANTE', id_estado: 12 },
	];

	//
	let i: number = (data.length - 1) / 3 + 1;
	const rangos: any[] = [
		{ init: 0, end: Math.round(i) },
		{ init: Math.round(i), end: Math.round(i * 2) },
		{ init: Math.round(i * 2), end: Math.round(data.length) },
	];

	const stop = rangos.map(async (item: { init: number; end: number }) => {
		const { init, end } = item;
		const info: fm_municipio[] = data.slice(init, end);
		const valid = await getRepository(fm_municipio).find({ where: info });
		if (!valid.length) await getRepository(fm_municipio).save(info);
	});
	await Promise.all(stop);
};

export default municipio;
