import { getRepository } from 'typeorm';
import fm_parroquia from '../models/fm_parroquia';

const parroquia = async (): Promise<void> => {
	const data: fm_parroquia[] = [
		{ id: 1, parroquia: 'ALTAGRACIA ', id_municipio: 1 },
		{ id: 2, parroquia: 'ANTIMANO ', id_municipio: 1 },
		{ id: 3, parroquia: 'CANDELARIA ', id_municipio: 1 },
		{ id: 4, parroquia: 'CARICUAO ', id_municipio: 1 },
		{ id: 5, parroquia: 'CATEDRAL ', id_municipio: 1 },
		{ id: 6, parroquia: 'COCHE ', id_municipio: 1 },
		{ id: 7, parroquia: 'EL JUNQUITO ', id_municipio: 1 },
		{ id: 8, parroquia: 'EL PARAISO ', id_municipio: 1 },
		{ id: 9, parroquia: 'EL RECREO ', id_municipio: 1 },
		{ id: 10, parroquia: 'EL VALLE ', id_municipio: 1 },
		{ id: 11, parroquia: 'LA PASTORA ', id_municipio: 1 },
		{ id: 12, parroquia: 'LA VEGA ', id_municipio: 1 },
		{ id: 13, parroquia: 'MACARAO ', id_municipio: 1 },
		{ id: 14, parroquia: 'SAN AGUSTIN ', id_municipio: 1 },
		{ id: 15, parroquia: 'SAN BERNARDINO ', id_municipio: 1 },
		{ id: 16, parroquia: 'SAN JOSE ', id_municipio: 1 },
		{ id: 17, parroquia: 'SAN JUAN ', id_municipio: 1 },
		{ id: 18, parroquia: 'SAN PEDRO ', id_municipio: 1 },
		{ id: 19, parroquia: 'SANTA ROSALIA ', id_municipio: 1 },
		{ id: 20, parroquia: 'SANTA TERESA ', id_municipio: 1 },
		{ id: 21, parroquia: 'SUCRE ', id_municipio: 1 },
		{ id: 22, parroquia: '23 DE ENERO ', id_municipio: 1 },
		{ id: 23, parroquia: 'CAPITAL ALTO ORINOCO ', id_municipio: 1 },
		{ id: 24, parroquia: 'UCATA ', id_municipio: 2 },
		{ id: 25, parroquia: 'NO URBANA PAO DE ZARATE ', id_municipio: 3 },
		{ id: 26, parroquia: 'PARAISO DE SAN JOSE ', id_municipio: 3 },
		{ id: 27, parroquia: 'SAMARIAPO ', id_municipio: 4 },
		{ id: 28, parroquia: 'VICTORINO ', id_municipio: 5 },
		{ id: 29, parroquia: 'ALTO VENTUARI ', id_municipio: 6 },
		{ id: 30, parroquia: 'CAPITAL RIO NEGRO ', id_municipio: 7 },
		{ id: 31, parroquia: 'CAPITAL ANACO ', id_municipio: 1 },
		{ id: 32, parroquia: 'SAN JOAQUIN ', id_municipio: 1 },
		{ id: 33, parroquia: 'CAPITAL ARAGUA ', id_municipio: 2 },
		{ id: 34, parroquia: 'CACHIPO ', id_municipio: 2 },
		{ id: 35, parroquia: 'CAPITAL FERNANDO DE PEÑAS', id_municipio: 3 },
		{ id: 36, parroquia: 'SAN MIGUEL ', id_municipio: 3 },
		{ id: 37, parroquia: 'SUCRE ', id_municipio: 3 },
		{ id: 38, parroquia: 'VALLE DE GUANAPE ', id_municipio: 4 },
		{ id: 39, parroquia: 'SANTA ROSALIA ', id_municipio: 4 },
		{ id: 40, parroquia: 'CAPITAL FRANCISCO DE MIRANDA ', id_municipio: 5 },
		{ id: 41, parroquia: 'ATAPIRIRE ', id_municipio: 5 },
		{ id: 42, parroquia: 'BOCA DEL PAO ', id_municipio: 5 },
		{ id: 43, parroquia: 'EL PAO ', id_municipio: 5 },
		{ id: 44, parroquia: 'GUANTA ', id_municipio: 6 },
		{ id: 45, parroquia: 'PARHUEÑA', id_municipio: 3 },
		{ id: 46, parroquia: 'CAPITAL INDEPENDENCIA ', id_municipio: 7 },
		{ id: 47, parroquia: 'MAMO ', id_municipio: 7 },
		{ id: 48, parroquia: 'CAPITAL PUERTO LA CRUZ ', id_municipio: 8 },
		{ id: 49, parroquia: 'POZUELOS ', id_municipio: 8 },
		{ id: 50, parroquia: 'CAPITAL ONOTO ', id_municipio: 9 },
		{ id: 51, parroquia: 'SAN PABLO ', id_municipio: 9 },
		{ id: 52, parroquia: 'CAPITAL JOSE GREGORIO MONAGAS ', id_municipio: 10 },
		{ id: 53, parroquia: 'PIAR ', id_municipio: 10 },
		{ id: 54, parroquia: 'SAN DIEGO DE CABRUTICA ', id_municipio: 10 },
		{ id: 55, parroquia: 'SANTA CLARA ', id_municipio: 10 },
		{ id: 56, parroquia: 'UVERITO ', id_municipio: 10 },
		{ id: 57, parroquia: 'ZUATA ', id_municipio: 10 },
		{ id: 58, parroquia: 'CAPITAL LIBERTAD ', id_municipio: 11 },
		{ id: 59, parroquia: 'EL CARITO ', id_municipio: 11 },
		{ id: 60, parroquia: 'SANTA INES ', id_municipio: 11 },
		{ id: 61, parroquia: 'CAPITAL CLARINES ', id_municipio: 12 },
		{ id: 62, parroquia: 'GUANAPE ', id_municipio: 12 },
		{ id: 63, parroquia: 'SABANA DE UCHIRE ', id_municipio: 12 },
		{ id: 64, parroquia: 'CAPITAL PEDRO MARIA FREITES ', id_municipio: 13 },
		{ id: 65, parroquia: 'LIBERTADOR ', id_municipio: 13 },
		{ id: 66, parroquia: 'SANTA ROSA ', id_municipio: 13 },
		{ id: 67, parroquia: 'URICA ', id_municipio: 13 },
		{ id: 68, parroquia: 'CAPITAL PIRITU ', id_municipio: 14 },
		{ id: 69, parroquia: 'SAN FRANCISCO ', id_municipio: 14 },
		{ id: 70, parroquia: 'CAPITAL SAN JOSE DE GUANIPA ', id_municipio: 15 },
		{ id: 71, parroquia: 'CAPITAL BOCA DE UCHIRE ', id_municipio: 16 },
		{ id: 72, parroquia: 'BOCA DE CHAVEZ ', id_municipio: 16 },
		{ id: 73, parroquia: 'CAPITAL SANTA ANA ', id_municipio: 17 },
		{ id: 74, parroquia: 'PUEBLO NUEVO ', id_municipio: 17 },
		{ id: 75, parroquia: 'EL CARMEN ', id_municipio: 18 },
		{ id: 76, parroquia: 'SAN CRISTOBAL ', id_municipio: 18 },
		{ id: 77, parroquia: 'BERGANTIN ', id_municipio: 18 },
		{ id: 78, parroquia: 'CAIGUA ', id_municipio: 18 },
		{ id: 79, parroquia: 'EL PILAR ', id_municipio: 18 },
		{ id: 80, parroquia: 'SANTA INUS ', id_municipio: 18 },
		{ id: 81, parroquia: 'P. CAPITAL SIMON RODRIGUEZ ', id_municipio: 19 },
		{ id: 82, parroquia: 'EL CHAPARRO ', id_municipio: 20 },
		{ id: 83, parroquia: 'TOMAS ALFARO CALATRAVA ', id_municipio: 20 },
		{ id: 84, parroquia: 'LECHERIAS ', id_municipio: 21 },
		{ id: 85, parroquia: 'EL MORRO ', id_municipio: 21 },
		{ id: 86, parroquia: 'URBANA ACHAGUAS ', id_municipio: 1 },
		{ id: 87, parroquia: 'APURITO ', id_municipio: 1 },
		{ id: 88, parroquia: 'EL YAGUAL ', id_municipio: 1 },
		{ id: 89, parroquia: 'GUACHARA ', id_municipio: 1 },
		{ id: 90, parroquia: 'MUCURITAS ', id_municipio: 1 },
		{ id: 91, parroquia: 'QUESERAS DEL MEDIO ', id_municipio: 1 },
		{ id: 92, parroquia: 'URBANA BIRUACA ', id_municipio: 2 },
		{ id: 93, parroquia: 'URBANA BRUZUAL ', id_municipio: 3 },
		{ id: 94, parroquia: 'MANTECAL ', id_municipio: 3 },
		{ id: 95, parroquia: 'QUINTERO ', id_municipio: 3 },
		{ id: 96, parroquia: 'RINCON HONDO ', id_municipio: 3 },
		{ id: 97, parroquia: 'SAN VICENTE ', id_municipio: 3 },
		{ id: 98, parroquia: 'URBANA GUASDUALITO ', id_municipio: 4 },
		{ id: 99, parroquia: 'ARAMENDI ', id_municipio: 4 },
		{ id: 100, parroquia: 'EL AMPARO ', id_municipio: 4 },
		{ id: 101, parroquia: 'SAN CAMILO ', id_municipio: 4 },
		{ id: 102, parroquia: 'URDANETA ', id_municipio: 4 },
		{ id: 103, parroquia: 'URBANA SAN JUAN DE PAYARA ', id_municipio: 5 },
		{ id: 104, parroquia: 'CODAZZI ', id_municipio: 5 },
		{ id: 105, parroquia: 'CUNAVICHE ', id_municipio: 5 },
		{ id: 106, parroquia: 'URBANA ELORZA ', id_municipio: 6 },
		{ id: 107, parroquia: 'LA TRINIDAD ', id_municipio: 6 },
		{ id: 108, parroquia: 'URBANA SAN FERNANDO ', id_municipio: 7 },
		{ id: 109, parroquia: 'EL RECREO ', id_municipio: 7 },
		{ id: 110, parroquia: 'PE&Ntilde', id_municipio: 4 },
		{ id: 111, parroquia: 'SAN RAFAEL DE ATAMAICA ', id_municipio: 7 },
		{ id: 112, parroquia: 'CAPITAL BOLIVAR ', id_municipio: 1 },
		{ id: 113, parroquia: 'CAPITAL CAMATAGUA ', id_municipio: 2 },
		{ id: 114, parroquia: 'NO URBANA CARMEN DE CURA ', id_municipio: 2 },
		{ id: 115, parroquia: 'NO URBANA CHORONI ', id_municipio: 3 },
		{ id: 116, parroquia: 'URBANA LAS DELICIAS ', id_municipio: 3 },
		{ id: 117, parroquia: 'URBANA M. MARIA DE S JOSE ', id_municipio: 3 },
		{ id: 118, parroquia: 'URBANA JOAQUIN CRESPO ', id_municipio: 3 },
		{ id: 119, parroquia: 'URBANA PEDRO JOSE OVALLES ', id_municipio: 3 },
		{ id: 120, parroquia: 'URBANA JOSE CASANOVA GODOY ', id_municipio: 3 },
		{ id: 121, parroquia: 'URBANA ANDRES ELOY BLANCO ', id_municipio: 3 },
		{ id: 122, parroquia: 'URBANA LOS TACARIGUAS ', id_municipio: 3 },
		{ id: 123, parroquia: 'CAPITAL JOSE ANGEL LAMAS ', id_municipio: 4 },
		{ id: 124, parroquia: 'CAPITAL JOSE FELIX RIBAS ', id_municipio: 5 },
		{ id: 125, parroquia: 'CASTOR NIEVES RIOS ', id_municipio: 5 },
		{ id: 126, parroquia: 'NO URBANA LAS GUACAMAYAS ', id_municipio: 5 },
		{ id: 127, parroquia: 'NO URBANA PAO DE ZARATE ', id_municipio: 5 },
		{ id: 128, parroquia: 'NO URBANA ZUATA ', id_municipio: 5 },
		{ id: 129, parroquia: 'CAPITAL DIAZ ', id_municipio: 6 },
		{ id: 130, parroquia: 'CAPITAL LIBERTADOR ', id_municipio: 7 },
		{ id: 131, parroquia: 'NO URBANA S MARTIN DE PORRES ', id_municipio: 7 },
		{ id: 132, parroquia: 'CAPITAL MARIO BRICE&Ntilde', id_municipio: 5 },
		{ id: 133, parroquia: 'CA&Ntilde', id_municipio: 5 },
		{ id: 134, parroquia: 'CAPITAL SAN CASIMIRO ', id_municipio: 9 },
		{ id: 135, parroquia: 'NO URBANA GUIRIPA ', id_municipio: 9 },
		{ id: 136, parroquia: 'NO URBANA OLLAS DE CARAMACATE ', id_municipio: 9 },
		{ id: 137, parroquia: 'NO URBANA VALLE MORIN ', id_municipio: 9 },
		{ id: 138, parroquia: 'CAPITAL SAN SEBASTIAN ', id_municipio: 10 },
		{ id: 139, parroquia: 'CAPITAL SANTIAGO MARI&Ntilde', id_municipio: 5 },
		{ id: 140, parroquia: 'NO URBANA ARAVALO APONTE ', id_municipio: 11 },
		{ id: 141, parroquia: 'NO URBANA CHUAO ', id_municipio: 11 },
		{ id: 142, parroquia: 'NO URBANA SAMAN DE GUERE ', id_municipio: 11 },
		{ id: 143, parroquia: 'NO URBANA ALFREDO PACHECO M ', id_municipio: 11 },
		{ id: 144, parroquia: 'CAPITAL SANTOS MICHELENA ', id_municipio: 12 },
		{ id: 145, parroquia: 'NO URBANA TIARA ', id_municipio: 12 },
		{ id: 146, parroquia: 'CAPITAL SUCRE ', id_municipio: 13 },
		{ id: 147, parroquia: 'NO URBANA BELLA VISTA ', id_municipio: 13 },
		{ id: 148, parroquia: 'CAPITAL TOVAR ', id_municipio: 14 },
		{ id: 149, parroquia: 'CAPITAL URDANETA ', id_municipio: 15 },
		{ id: 150, parroquia: 'NO URBANA LAS PE&Ntilde', id_municipio: 5 },
		{ id: 151, parroquia: 'NO URBANA SAN FRANCISCO DE C ', id_municipio: 15 },
		{ id: 152, parroquia: 'NO URBANA TAGUAY ', id_municipio: 15 },
		{ id: 153, parroquia: 'CAPITAL ZAMORA ', id_municipio: 16 },
		{ id: 154, parroquia: 'NO URBANA MAGDALENO ', id_municipio: 16 },
		{ id: 155, parroquia: 'NO URBANA S FRANCISCO DE ASIS ', id_municipio: 16 },
		{ id: 156, parroquia: 'NO URBANA VALLES DE TUCUTUNEMO ', id_municipio: 16 },
		{ id: 157, parroquia: 'NO URBANA AUGUSTO MIJARES ', id_municipio: 16 },
		{ id: 158, parroquia: 'CAPITAL FRANCISCO LINARES A. ', id_municipio: 17 },
		{ id: 159, parroquia: 'NO URBANA FRANCISCO DE MIRANDA ', id_municipio: 17 },
		{ id: 160, parroquia: 'NO URBANA MONSE&Ntilde', id_municipio: 5 },
		{ id: 161, parroquia: 'CAPITAL OCM DE LA COSTA DE ORO ', id_municipio: 18 },
		{ id: 162, parroquia: 'SABANETA ', id_municipio: 1 },
		{ id: 163, parroquia: 'RODRIGUEZ DOMINGUEZ ', id_municipio: 1 },
		{ id: 164, parroquia: 'TICOPORO ', id_municipio: 2 },
		{ id: 165, parroquia: 'ANDRES BELLO ', id_municipio: 2 },
		{ id: 166, parroquia: 'NICOLAS PULIDO ', id_municipio: 2 },
		{ id: 167, parroquia: 'ARISMENDI ', id_municipio: 3 },
		{ id: 168, parroquia: 'GUADARRAMA ', id_municipio: 3 },
		{ id: 169, parroquia: 'LA UNION ', id_municipio: 3 },
		{ id: 170, parroquia: 'SAN ANTONIO ', id_municipio: 3 },
		{ id: 171, parroquia: 'BARINAS ', id_municipio: 4 },
		{ id: 172, parroquia: 'ALFREDO ARVELO LARRIVA ', id_municipio: 4 },
		{ id: 173, parroquia: 'SAN SILVESTRE ', id_municipio: 4 },
		{ id: 174, parroquia: 'SANTA INES ', id_municipio: 4 },
		{ id: 175, parroquia: 'SANTA LUCIA ', id_municipio: 4 },
		{ id: 176, parroquia: 'TORUNOS ', id_municipio: 4 },
		{ id: 177, parroquia: 'EL CARMEN ', id_municipio: 4 },
		{ id: 178, parroquia: 'ROMULO BETANCOURT ', id_municipio: 4 },
		{ id: 179, parroquia: 'CHIQUINQUIRA ', id_municipio: 4 },
		{ id: 180, parroquia: 'RAMON IGNACIO MENDEZ ', id_municipio: 4 },
		{ id: 181, parroquia: 'ALTO BARINAS ', id_municipio: 4 },
		{ id: 182, parroquia: 'MANUEL PALACIO FAJARDO ', id_municipio: 4 },
		{ id: 183, parroquia: 'JUAN A RODRIGUEZ DOMINGUEZ ', id_municipio: 4 },
		{ id: 184, parroquia: 'DOMINGA ORTIZ DE PEREZ ', id_municipio: 4 },
		{ id: 185, parroquia: 'BARINITAS ', id_municipio: 5 },
		{ id: 186, parroquia: 'ALTAMIRA ', id_municipio: 5 },
		{ id: 187, parroquia: 'CALDERAS ', id_municipio: 5 },
		{ id: 188, parroquia: 'BARRANCAS ', id_municipio: 6 },
		{ id: 189, parroquia: 'EL SOCORRO ', id_municipio: 6 },
		{ id: 190, parroquia: 'MASPARRITO ', id_municipio: 6 },
		{ id: 191, parroquia: 'SANTA BARBARA ', id_municipio: 7 },
		{ id: 192, parroquia: 'JOSE IGNACIO DEL PUMAR ', id_municipio: 7 },
		{ id: 193, parroquia: 'PEDRO BRICEÑO', id_municipio: 6 },
		{ id: 194, parroquia: 'RAMON IGNACIO MENDEZ ', id_municipio: 7 },
		{ id: 195, parroquia: 'OBISPOS ', id_municipio: 8 },
		{ id: 196, parroquia: 'EL REAL ', id_municipio: 8 },
		{ id: 197, parroquia: 'LA LUZ ', id_municipio: 8 },
		{ id: 198, parroquia: 'LOS GUASIMITOS ', id_municipio: 8 },
		{ id: 199, parroquia: 'CIUDAD BOLIVIA ', id_municipio: 9 },
		{ id: 200, parroquia: 'IGNACIO BRICEÑO', id_municipio: 6 },
		{ id: 201, parroquia: 'JOSE FELIX RIBAS ', id_municipio: 9 },
		{ id: 202, parroquia: 'PAEZ ', id_municipio: 9 },
		{ id: 203, parroquia: 'LIBERTAD ', id_municipio: 10 },
		{ id: 204, parroquia: 'DOLORES ', id_municipio: 10 },
		{ id: 205, parroquia: 'PALACIOS FAJARDO ', id_municipio: 10 },
		{ id: 206, parroquia: 'SANTA ROSA ', id_municipio: 10 },
		{ id: 207, parroquia: 'CIUDAD DE NUTRIAS ', id_municipio: 11 },
		{ id: 208, parroquia: 'EL REGALO ', id_municipio: 11 },
		{ id: 209, parroquia: 'PUERTO DE NUTRIAS ', id_municipio: 11 },
		{ id: 210, parroquia: 'SANTA CATALINA ', id_municipio: 11 },
		{ id: 211, parroquia: 'EL CANTON ', id_municipio: 12 },
		{ id: 212, parroquia: 'SANTA CRUZ DE GUACAS ', id_municipio: 12 },
		{ id: 213, parroquia: 'PUERTO VIVAS ', id_municipio: 12 },
		{ id: 214, parroquia: 'CACHAMAY ', id_municipio: 1 },
		{ id: 215, parroquia: 'CHIRICA ', id_municipio: 67 },
		{ id: 216, parroquia: 'DALLA COSTA ', id_municipio: 1 },
		{ id: 217, parroquia: 'ONCE DE ABRIL ', id_municipio: 1 },
		{ id: 218, parroquia: 'SIMON BOLIVAR ', id_municipio: 1 },
		{ id: 219, parroquia: 'UNARE ', id_municipio: 1 },
		{ id: 220, parroquia: 'UNIVERSIDAD ', id_municipio: 1 },
		{ id: 221, parroquia: 'VISTA AL SOL ', id_municipio: 1 },
		{ id: 222, parroquia: 'POZO VERDE ', id_municipio: 1 },
		{ id: 223, parroquia: 'YOCOIMA ', id_municipio: 1 },
		{ id: 224, parroquia: 'SECCION CAPITAL CEDEÑA', id_municipio: 15 },
		{ id: 225, parroquia: 'ADRIAN ', id_municipio: 2 },
		{ id: 226, parroquia: 'ASCENSION FARRERAS ', id_municipio: 2 },
		{ id: 227, parroquia: 'GUIRIA ', id_municipio: 2 },
		{ id: 228, parroquia: 'LA URBANA ', id_municipio: 2 },
		{ id: 229, parroquia: 'PIJIGUAOS ', id_municipio: 2 },
		{ id: 230, parroquia: 'CAPITAL EL CALLAO ', id_municipio: 3 },
		{ id: 231, parroquia: 'SECCION CAPITAL GRAN SABANA ', id_municipio: 4 },
		{ id: 232, parroquia: 'IKABARU ', id_municipio: 4 },
		{ id: 233, parroquia: 'AGUA SALADA ', id_municipio: 5 },
		{ id: 234, parroquia: 'CATEDRAL ', id_municipio: 5 },
		{ id: 235, parroquia: 'JOSE ANTONIO PAEZ ', id_municipio: 5 },
		{ id: 236, parroquia: 'LA SABANITA ', id_municipio: 5 },
		{ id: 237, parroquia: 'MARHUANTA ', id_municipio: 5 },
		{ id: 238, parroquia: 'VISTA HERMOSA ', id_municipio: 5 },
		{ id: 239, parroquia: 'ORINOCO ', id_municipio: 5 },
		{ id: 240, parroquia: 'PANAPANA ', id_municipio: 5 },
		{ id: 241, parroquia: 'ZEA ', id_municipio: 5 },
		{ id: 242, parroquia: 'SECCION CAPITAL PIAR ', id_municipio: 6 },
		{ id: 243, parroquia: 'ANDRES ELOY BLANCO ', id_municipio: 6 },
		{ id: 244, parroquia: 'PEDRO COVA ', id_municipio: 6 },
		{ id: 245, parroquia: 'SECCION CAPITAL RAUL LEONI ', id_municipio: 7 },
		{ id: 246, parroquia: 'BARCELONETA ', id_municipio: 7 },
		{ id: 247, parroquia: 'SAN FRANCISCO ', id_municipio: 7 },
		{ id: 248, parroquia: 'SANTA BARBARA ', id_municipio: 7 },
		{ id: 249, parroquia: 'SECCION CAPITAL ROSCIO ', id_municipio: 8 },
		{ id: 250, parroquia: 'SALOM ', id_municipio: 8 },
		{ id: 251, parroquia: 'SECCION CAPITAL SIFONTES ', id_municipio: 9 },
		{ id: 252, parroquia: 'DALLA COSTA ', id_municipio: 9 },
		{ id: 253, parroquia: 'SAN ISIDRO ', id_municipio: 9 },
		{ id: 254, parroquia: 'SECCION CAPITAL SUCRE ', id_municipio: 10 },
		{ id: 255, parroquia: 'ARIPAO ', id_municipio: 10 },
		{ id: 256, parroquia: 'GUARATARO ', id_municipio: 10 },
		{ id: 257, parroquia: 'LAS MAJADAS ', id_municipio: 10 },
		{ id: 258, parroquia: 'MOITACO ', id_municipio: 10 },
		{ id: 259, parroquia: 'CAPITAL PADRE PEDRO CHIEN ', id_municipio: 11 },
		{ id: 260, parroquia: 'URBANA BEJUMA ', id_municipio: 1 },
		{ id: 261, parroquia: 'NO URBANA CANOABO ', id_municipio: 1 },
		{ id: 262, parroquia: 'NO URBANA SIMON BOLIVAR ', id_municipio: 1 },
		{ id: 263, parroquia: 'URBANA GUIGUE ', id_municipio: 2 },
		{ id: 264, parroquia: 'NO URBANA BELUN ', id_municipio: 2 },
		{ id: 265, parroquia: 'NO URBANA TACARIGUA ', id_municipio: 2 },
		{ id: 266, parroquia: 'URBANA AGUAS CALIENTES ', id_municipio: 3 },
		{ id: 267, parroquia: 'URBANA MARIARA ', id_municipio: 3 },
		{ id: 268, parroquia: 'URBANA CIUDAD ALIANZA ', id_municipio: 4 },
		{ id: 269, parroquia: 'URBANA GUACARA ', id_municipio: 4 },
		{ id: 270, parroquia: 'NO URBANA YAGUA ', id_municipio: 4 },
		{ id: 271, parroquia: 'URBANA MORON ', id_municipio: 5 },
		{ id: 272, parroquia: 'NO URBANA URAMA ', id_municipio: 5 },
		{ id: 273, parroquia: 'URBANA TOCUYITO ', id_municipio: 6 },
		{ id: 274, parroquia: 'URBANA INDEPENDENCIA ', id_municipio: 6 },
		{ id: 275, parroquia: 'URBANA LOS GUAYOS ', id_municipio: 7 },
		{ id: 276, parroquia: 'URBANA MIRANDA ', id_municipio: 8 },
		{ id: 277, parroquia: 'URBANA MONTALBAN ', id_municipio: 9 },
		{ id: 278, parroquia: 'URBANA NAGUANAGUA ', id_municipio: 10 },
		{ id: 279, parroquia: 'URBANA BARTOLOME SALOM ', id_municipio: 11 },
		{ id: 280, parroquia: 'URBANA DEMOCRACIA ', id_municipio: 11 },
		{ id: 281, parroquia: 'URBANA FRATERNIDAD ', id_municipio: 11 },
		{ id: 282, parroquia: 'URBANA GOAIGOAZA ', id_municipio: 11 },
		{ id: 283, parroquia: 'URBANA JUAN JOSE FLORES ', id_municipio: 11 },
		{ id: 284, parroquia: 'URBANA UNION ', id_municipio: 11 },
		{ id: 285, parroquia: 'NO URBANA BORBURATA ', id_municipio: 11 },
		{ id: 286, parroquia: 'NICOLAS PULIDO ', id_municipio: 11 },
		{ id: 287, parroquia: 'URBANA SAN DIEGO ', id_municipio: 12 },
		{ id: 288, parroquia: 'URBANA SAN JOAQUIN ', id_municipio: 13 },
		{ id: 289, parroquia: 'URBANA CANDELARIA ', id_municipio: 14 },
		{ id: 290, parroquia: 'URBANA CATEDRAL ', id_municipio: 14 },
		{ id: 291, parroquia: 'URBANA EL SOCORRO ', id_municipio: 14 },
		{ id: 292, parroquia: 'URBANA MIGUEL PEÑA', id_municipio: 8 },
		{ id: 293, parroquia: 'URBANA RAFAEL URDANETA ', id_municipio: 14 },
		{ id: 294, parroquia: 'URBANA GUIGUE ', id_municipio: 14 },
		{ id: 295, parroquia: 'URBANA SAN JOSE ', id_municipio: 14 },
		{ id: 296, parroquia: 'URBANA SANTA ROSA ', id_municipio: 14 },
		{ id: 297, parroquia: 'NO URBANA NEGRO PRIMERO ', id_municipio: 14 },
		{ id: 298, parroquia: 'COJEDES ', id_municipio: 1 },
		{ id: 299, parroquia: 'JUAN DE MATA SUAREZ ', id_municipio: 1 },
		{ id: 300, parroquia: 'TINAQUILLO ', id_municipio: 2 },
		{ id: 301, parroquia: 'EL BAUL ', id_municipio: 3 },
		{ id: 302, parroquia: 'SUCRE ', id_municipio: 3 },
		{ id: 303, parroquia: 'MACAPO ', id_municipio: 4 },
		{ id: 304, parroquia: 'LA AGUADITA ', id_municipio: 4 },
		{ id: 305, parroquia: 'EL PAO ', id_municipio: 5 },
		{ id: 306, parroquia: 'LIBERTAD DE COJEDES ', id_municipio: 6 },
		{ id: 307, parroquia: 'EL AMPARO ', id_municipio: 6 },
		{ id: 308, parroquia: 'ROMULO GALLEGOS ', id_municipio: 7 },
		{ id: 309, parroquia: 'SAN CARLOS DE AUSTRIA ', id_municipio: 8 },
		{ id: 310, parroquia: 'JUAN ANGEL BRAVO ', id_municipio: 8 },
		{ id: 311, parroquia: 'MANUEL MANRIQUE ', id_municipio: 8 },
		{ id: 312, parroquia: 'GENERAL JOSE LAURENCIO SILVA ', id_municipio: 9 },
		{ id: 313, parroquia: 'CURIAPO ', id_municipio: 1 },
		{ id: 314, parroquia: 'ALMIRANTE LUIS BRION ', id_municipio: 1 },
		{ id: 315, parroquia: 'FRANCISCO ANICETO LUGO ', id_municipio: 1 },
		{ id: 316, parroquia: 'MANUEL RENAUD ', id_municipio: 1 },
		{ id: 317, parroquia: 'PADRE BARRAL ', id_municipio: 1 },
		{ id: 318, parroquia: 'SANTOS DE ABELGAS ', id_municipio: 1 },
		{ id: 319, parroquia: 'IMATACA ', id_municipio: 2 },
		{ id: 320, parroquia: 'CINCO DE JULIO ', id_municipio: 2 },
		{ id: 321, parroquia: 'JUAN BAUTISTA ARISMENDI ', id_municipio: 2 },
		{ id: 322, parroquia: 'MANUEL PIAR ', id_municipio: 2 },
		{ id: 323, parroquia: 'ROMULO GALLEGOS ', id_municipio: 2 },
		{ id: 324, parroquia: 'PEDERNALES ', id_municipio: 3 },
		{ id: 325, parroquia: 'LUIS BELTRAN PRIETO FIGUEROA ', id_municipio: 3 },
		{ id: 326, parroquia: 'SAN JOSE ', id_municipio: 4 },
		{ id: 327, parroquia: 'JOSE VIDAL MARCANO ', id_municipio: 4 },
		{ id: 328, parroquia: 'JUAN MILLAN ', id_municipio: 4 },
		{ id: 329, parroquia: 'LEONARDO RUIZ PINEDA ', id_municipio: 4 },
		{ id: 330, parroquia: 'MARISCAL ANTONIO JOSE DE SUCRE ', id_municipio: 4 },
		{ id: 331, parroquia: 'MARIA DE LA C PALACIOS BLANCO ', id_municipio: 4 },
		{ id: 332, parroquia: 'SAN RAFAEL ', id_municipio: 4 },
		{ id: 333, parroquia: 'VIRGEN DEL VALLE ', id_municipio: 4 },
		{ id: 334, parroquia: 'SAN JUAN DE LOS CAYOS ', id_municipio: 1 },
		{ id: 335, parroquia: 'CAPADARE ', id_municipio: 1 },
		{ id: 336, parroquia: 'LA PASTORA ', id_municipio: 1 },
		{ id: 337, parroquia: 'LIBERTADOR ', id_municipio: 1 },
		{ id: 338, parroquia: 'SAN LUIS ', id_municipio: 2 },
		{ id: 339, parroquia: 'ARACUA ', id_municipio: 2 },
		{ id: 340, parroquia: 'LA PEÑA', id_municipio: 11 },
		{ id: 341, parroquia: 'CAPATARIDA ', id_municipio: 3 },
		{ id: 342, parroquia: 'BARIRO ', id_municipio: 3 },
		{ id: 343, parroquia: 'BOROJO ', id_municipio: 3 },
		{ id: 344, parroquia: 'GUAJIRO ', id_municipio: 3 },
		{ id: 345, parroquia: 'SEQUE ', id_municipio: 3 },
		{ id: 346, parroquia: 'ZAZARIDA ', id_municipio: 3 },
		{ id: 347, parroquia: 'CAPITAL CACIQUE MANAURE ', id_municipio: 4 },
		{ id: 348, parroquia: 'CARIRUBANA ', id_municipio: 5 },
		{ id: 349, parroquia: 'NORTE ', id_municipio: 5 },
		{ id: 350, parroquia: 'PUNTA CARDON ', id_municipio: 5 },
		{ id: 351, parroquia: 'SANTA ANA ', id_municipio: 5 },
		{ id: 352, parroquia: 'LA VELA DE CORO ', id_municipio: 6 },
		{ id: 353, parroquia: 'ACURIGUA ', id_municipio: 6 },
		{ id: 354, parroquia: 'GUAIBACOA ', id_municipio: 6 },
		{ id: 355, parroquia: 'LAS CALDERAS ', id_municipio: 6 },
		{ id: 356, parroquia: 'MACORUCA ', id_municipio: 6 },
		{ id: 357, parroquia: 'CAPITAL DABAJURO ', id_municipio: 7 },
		{ id: 358, parroquia: 'PEDREGAL ', id_municipio: 8 },
		{ id: 359, parroquia: 'AGUA CLARA ', id_municipio: 8 },
		{ id: 360, parroquia: 'AVARIA ', id_municipio: 8 },
		{ id: 361, parroquia: 'PIEDRA GRANDE ', id_municipio: 8 },
		{ id: 362, parroquia: 'PURURECHE ', id_municipio: 8 },
		{ id: 363, parroquia: 'PUEBLO NUEVO ', id_municipio: 9 },
		{ id: 364, parroquia: 'ADICORA ', id_municipio: 9 },
		{ id: 365, parroquia: 'BARAIVED ', id_municipio: 9 },
		{ id: 366, parroquia: 'BUENA VISTA ', id_municipio: 9 },
		{ id: 367, parroquia: 'JADACAQUIVA ', id_municipio: 9 },
		{ id: 368, parroquia: 'MORUY ', id_municipio: 9 },
		{ id: 369, parroquia: 'ADAURE ', id_municipio: 9 },
		{ id: 370, parroquia: 'EL CAFE ', id_municipio: 9 },
		{ id: 371, parroquia: 'EL VINCULO ', id_municipio: 9 },
		{ id: 372, parroquia: 'CHURUGUARA ', id_municipio: 10 },
		{ id: 373, parroquia: 'AGUA LARGA ', id_municipio: 10 },
		{ id: 374, parroquia: 'EL PAUJI ', id_municipio: 10 },
		{ id: 375, parroquia: 'INDEPENDENCIA ', id_municipio: 10 },
		{ id: 376, parroquia: 'MAPARARI ', id_municipio: 10 },
		{ id: 377, parroquia: 'JACURA ', id_municipio: 11 },
		{ id: 378, parroquia: 'AGUA LINDA ', id_municipio: 11 },
		{ id: 379, parroquia: 'ARAURIMA ', id_municipio: 11 },
		{ id: 380, parroquia: 'LEONCIO MARTINEZ ', id_municipio: 12 },
		{ id: 381, parroquia: 'JUDIBANA ', id_municipio: 12 },
		{ id: 382, parroquia: 'MENE DE MAUROA ', id_municipio: 13 },
		{ id: 383, parroquia: 'CASIGUA ', id_municipio: 13 },
		{ id: 384, parroquia: 'SAN FELIX ', id_municipio: 13 },
		{ id: 385, parroquia: 'SAN ANTONIO ', id_municipio: 14 },
		{ id: 386, parroquia: 'SAN GABRIEL ', id_municipio: 14 },
		{ id: 387, parroquia: 'SANTA ANA ', id_municipio: 14 },
		{ id: 388, parroquia: 'GUZMAN GUILLERMO ', id_municipio: 14 },
		{ id: 389, parroquia: 'MITARE ', id_municipio: 14 },
		{ id: 390, parroquia: 'RIO SECO ', id_municipio: 14 },
		{ id: 391, parroquia: 'SABANETA ', id_municipio: 14 },
		{ id: 392, parroquia: 'CHICHIRIVICHE ', id_municipio: 119 },
		{ id: 393, parroquia: 'BOCA DE TOCUYO ', id_municipio: 15 },
		{ id: 394, parroquia: 'TOCUYO DE LA COSTA ', id_municipio: 15 },
		{ id: 395, parroquia: 'CAPITAL PALMASOLA ', id_municipio: 16 },
		{ id: 396, parroquia: 'CABURE ', id_municipio: 17 },
		{ id: 397, parroquia: 'COLINA ', id_municipio: 17 },
		{ id: 398, parroquia: 'CONCEPCION ', id_municipio: 17 },
		{ id: 399, parroquia: 'PIRITU ', id_municipio: 18 },
		{ id: 400, parroquia: 'SAN JOSE DE LA COSTA ', id_municipio: 18 },
		{ id: 401, parroquia: 'CAPITAL SAN FRANCISCO ', id_municipio: 19 },
		{ id: 402, parroquia: 'TUCACAS ', id_municipio: 20 },
		{ id: 403, parroquia: 'BOCA DE AROA ', id_municipio: 20 },
		{ id: 404, parroquia: 'SUCRE ', id_municipio: 21 },
		{ id: 405, parroquia: 'PECAYA ', id_municipio: 21 },
		{ id: 406, parroquia: 'CAPITAL TOCOPERO ', id_municipio: 22 },
		{ id: 407, parroquia: 'SANTA CRUZ DE BUCARAL ', id_municipio: 23 },
		{ id: 408, parroquia: 'EL CHARAL ', id_municipio: 23 },
		{ id: 409, parroquia: 'LAS VEGAS DEL TUY ', id_municipio: 23 },
		{ id: 410, parroquia: 'URUMACO ', id_municipio: 24 },
		{ id: 411, parroquia: 'BRUZUAL ', id_municipio: 24 },
		{ id: 412, parroquia: 'PUERTO CUMAREBO ', id_municipio: 25 },
		{ id: 413, parroquia: 'LA CIENAGA ', id_municipio: 25 },
		{ id: 414, parroquia: 'LA SOLEDAD ', id_municipio: 25 },
		{ id: 415, parroquia: 'PUEBLO CUMAREBO ', id_municipio: 25 },
		{ id: 416, parroquia: 'ZAZARIDA ', id_municipio: 25 },
		{ id: 417, parroquia: 'CAPITAL CAMAGUAN ', id_municipio: 1 },
		{ id: 418, parroquia: 'PUERTO MIRANDA ', id_municipio: 1 },
		{ id: 419, parroquia: 'UVERITO ', id_municipio: 1 },
		{ id: 420, parroquia: 'CHAGUARAMAS ', id_municipio: 2 },
		{ id: 421, parroquia: 'EL SOCORRO ', id_municipio: 3 },
		{ id: 422, parroquia: 'CAPITAL S GERONIM. DE GUAYABAL ', id_municipio: 4 },
		{ id: 423, parroquia: 'CAZORLA ', id_municipio: 4 },
		{ id: 424, parroquia: 'CAPITAL VALLE DE LA PASCUA ', id_municipio: 5 },
		{ id: 425, parroquia: 'ESPINO ', id_municipio: 5 },
		{ id: 426, parroquia: 'CAPITAL LAS MERCEDES ', id_municipio: 6 },
		{ id: 427, parroquia: 'CABRUTA ', id_municipio: 6 },
		{ id: 428, parroquia: 'SANTA RITA DE MANAPIRE ', id_municipio: 6 },
		{ id: 429, parroquia: 'CAPITAL EL SOMBRERO ', id_municipio: 7 },
		{ id: 430, parroquia: 'SOSA ', id_municipio: 7 },
		{ id: 431, parroquia: 'CAPITAL CALABOZO ', id_municipio: 8 },
		{ id: 432, parroquia: 'EL CALVARIO ', id_municipio: 8 },
		{ id: 433, parroquia: 'EL RASTRO ', id_municipio: 8 },
		{ id: 434, parroquia: 'GUARDATINAJAS ', id_municipio: 8 },
		{ id: 435, parroquia: 'CAPITAL ALTAGRACIA DE ORITUCO ', id_municipio: 9 },
		{ id: 436, parroquia: 'LA UNION ', id_municipio: 9 },
		{ id: 437, parroquia: 'LIBERTAD DE ORITUCO ', id_municipio: 9 },
		{ id: 438, parroquia: 'PASO REAL DE MACAIRA ', id_municipio: 9 },
		{ id: 439, parroquia: 'SAN FRANCISCO DE MACAIRA ', id_municipio: 9 },
		{ id: 440, parroquia: 'SAN RAFAEL DE ORITUCO ', id_municipio: 9 },
		{ id: 441, parroquia: 'SOUBLETTE ', id_municipio: 9 },
		{ id: 442, parroquia: 'CAPITAL JUSTO BRICEÑO', id_municipio: 12 },
		{ id: 443, parroquia: 'SAN FRANCISCO DE TIZNADOS ', id_municipio: 10 },
		{ id: 444, parroquia: 'SAN JOSE DE TIZNADOS ', id_municipio: 10 },
		{ id: 445, parroquia: 'SAN LORENZO DE TIZNADOS ', id_municipio: 10 },
		{ id: 446, parroquia: 'CAPITAL TUCUPIDO ', id_municipio: 11 },
		{ id: 447, parroquia: 'SAN RAFAEL DE LAYA ', id_municipio: 11 },
		{ id: 448, parroquia: 'CAPITAL SAN JUAN DE LOS MORROS ', id_municipio: 12 },
		{ id: 449, parroquia: 'CANTAGALLO ', id_municipio: 12 },
		{ id: 450, parroquia: 'PARAPARA ', id_municipio: 12 },
		{ id: 451, parroquia: 'SAN JOSE DE GUARIBE ', id_municipio: 13 },
		{ id: 452, parroquia: 'CAPITAL SANTA MARIA DE IPIRE ', id_municipio: 14 },
		{ id: 453, parroquia: 'ALTAMIRA ', id_municipio: 14 },
		{ id: 454, parroquia: 'CAPITAL SIMON RODRIGUEZ ', id_municipio: 15 },
		{ id: 455, parroquia: 'SAN JOSE DE UNARE ', id_municipio: 15 },
		{ id: 456, parroquia: 'PIO TAMAYO ', id_municipio: 1 },
		{ id: 457, parroquia: 'QUEBRADA HONDA DE GUACHE ', id_municipio: 1 },
		{ id: 458, parroquia: 'YACAMBU ', id_municipio: 1 },
		{ id: 459, parroquia: 'FREITEZ ', id_municipio: 2 },
		{ id: 460, parroquia: 'JOSE MARIA BLANCO ', id_municipio: 2 },
		{ id: 461, parroquia: 'CATEDRAL ', id_municipio: 3 },
		{ id: 462, parroquia: 'CONCEPCION ', id_municipio: 3 },
		{ id: 463, parroquia: 'EL CUJI ', id_municipio: 3 },
		{ id: 464, parroquia: 'JUAN DE VILLEGAS ', id_municipio: 3 },
		{ id: 465, parroquia: 'SANTA ROSA ', id_municipio: 3 },
		{ id: 466, parroquia: 'TAMACA ', id_municipio: 3 },
		{ id: 467, parroquia: 'UNION ', id_municipio: 3 },
		{ id: 468, parroquia: 'AGUEDO FELIPE ALVARADO ', id_municipio: 3 },
		{ id: 469, parroquia: 'BUENA VISTA ', id_municipio: 3 },
		{ id: 470, parroquia: 'JUAREZ ', id_municipio: 3 },
		{ id: 471, parroquia: 'JUAN BAUTISTA RODRIGUEZ ', id_municipio: 4 },
		{ id: 472, parroquia: 'CUARA ', id_municipio: 4 },
		{ id: 473, parroquia: 'DIEGO DE LOZADA ', id_municipio: 4 },
		{ id: 474, parroquia: 'PARAISO DE SAN JOSE ', id_municipio: 4 },
		{ id: 475, parroquia: 'SAN MIGUEL ', id_municipio: 4 },
		{ id: 476, parroquia: 'TINTORERO ', id_municipio: 4 },
		{ id: 477, parroquia: 'JOSE BERNARDO DORANTE ', id_municipio: 4 },
		{ id: 478, parroquia: 'CORONEL MARIANO PERAZA ', id_municipio: 4 },
		{ id: 479, parroquia: 'BOLIVAR ', id_municipio: 5 },
		{ id: 480, parroquia: 'ANZOATEGUI ', id_municipio: 5 },
		{ id: 481, parroquia: 'GERMAN RIOS LINARES ', id_municipio: 5 },
		{ id: 482, parroquia: 'HILARIO LUNA Y LUNA ', id_municipio: 5 },
		{ id: 483, parroquia: 'HUMOCARO ALTO ', id_municipio: 5 },
		{ id: 484, parroquia: 'HUMOCARO BAJO ', id_municipio: 5 },
		{ id: 485, parroquia: 'LA CANDELARIA ', id_municipio: 5 },
		{ id: 486, parroquia: 'MORAN ', id_municipio: 5 },
		{ id: 487, parroquia: 'CABUDARE ', id_municipio: 6 },
		{ id: 488, parroquia: 'JOSE GREGORIO BASTIDAS ', id_municipio: 6 },
		{ id: 489, parroquia: 'AGUA VIVA ', id_municipio: 6 },
		{ id: 490, parroquia: 'SARARE ', id_municipio: 7 },
		{ id: 491, parroquia: 'BURIA ', id_municipio: 7 },
		{ id: 492, parroquia: 'GUSTAVO VEGAS LEON ', id_municipio: 7 },
		{ id: 493, parroquia: 'TRINIDAD SAMUEL ', id_municipio: 8 },
		{ id: 494, parroquia: 'ANTONIO DIAZ ', id_municipio: 8 },
		{ id: 495, parroquia: 'CAMACARO ', id_municipio: 8 },
		{ id: 496, parroquia: 'CASTAÑO', id_municipio: 13 },
		{ id: 497, parroquia: 'CECILIO ZUBILLAGA ', id_municipio: 8 },
		{ id: 498, parroquia: 'CHIQUINQUIRA ', id_municipio: 8 },
		{ id: 499, parroquia: 'EL BLANCO ', id_municipio: 8 },
		{ id: 500, parroquia: 'ESPINOZA DE LOS MONTEROS ', id_municipio: 8 },
		{ id: 501, parroquia: 'LARA ', id_municipio: 8 },
		{ id: 502, parroquia: 'LAS MERCEDES ', id_municipio: 8 },
		{ id: 503, parroquia: 'MANUEL MORILLO ', id_municipio: 8 },
		{ id: 504, parroquia: 'MONTAÑA', id_municipio: 13 },
		{ id: 505, parroquia: 'MONTES DE OCA ', id_municipio: 8 },
		{ id: 506, parroquia: 'TORRES ', id_municipio: 8 },
		{ id: 507, parroquia: 'REYES VARGAS ', id_municipio: 8 },
		{ id: 508, parroquia: 'ALTAGRACIA ', id_municipio: 8 },
		{ id: 509, parroquia: 'SIQUISIQUE ', id_municipio: 9 },
		{ id: 510, parroquia: 'MOROTURO ', id_municipio: 9 },
		{ id: 511, parroquia: 'SAN MIGUEL ', id_municipio: 9 },
		{ id: 512, parroquia: 'XAGUAS ', id_municipio: 9 },
		{ id: 513, parroquia: 'PRESIDENTE BETANCOURT ', id_municipio: 1 },
		{ id: 514, parroquia: 'PRESIDENTE PAEZ ', id_municipio: 1 },
		{ id: 515, parroquia: 'PRESIDENTE ROMULO GALLEGOS ', id_municipio: 1 },
		{ id: 516, parroquia: 'GABRIEL PICON GONZALEZ ', id_municipio: 1 },
		{ id: 517, parroquia: 'HECTOR AMABLE MORA ', id_municipio: 1 },
		{ id: 518, parroquia: 'IDELFONSO VASQUEZ ', id_municipio: 1 },
		{ id: 519, parroquia: 'PULIDO MENDEZ ', id_municipio: 1 },
		{ id: 520, parroquia: 'CAPITAL ANDRES BELLO ', id_municipio: 2 },
		{ id: 521, parroquia: 'CAPITAL ANTONIO PINTO SALINAS ', id_municipio: 3 },
		{ id: 522, parroquia: 'MESA BOLIVAR ', id_municipio: 3 },
		{ id: 523, parroquia: 'MESA DE LAS PALMAS ', id_municipio: 3 },
		{ id: 524, parroquia: 'CAPITAL ARICAGUA ', id_municipio: 4 },
		{ id: 525, parroquia: 'SAN ANTONIO ', id_municipio: 4 },
		{ id: 526, parroquia: 'CAPITAL ARZOBISPO CHACON ', id_municipio: 5 },
		{ id: 527, parroquia: 'CAPURI ', id_municipio: 5 },
		{ id: 528, parroquia: 'CHACANTA ', id_municipio: 5 },
		{ id: 529, parroquia: 'EL MOLINO ', id_municipio: 5 },
		{ id: 530, parroquia: 'GUAIMARAL ', id_municipio: 5 },
		{ id: 531, parroquia: 'MUCUTUY ', id_municipio: 5 },
		{ id: 532, parroquia: 'MUCUCHACHI ', id_municipio: 5 },
		{ id: 533, parroquia: 'FERNANDEZ PEÑA', id_municipio: 14 },
		{ id: 534, parroquia: 'MATRIZ ', id_municipio: 6 },
		{ id: 535, parroquia: 'MONTALBAN ', id_municipio: 6 },
		{ id: 536, parroquia: 'ACEQUIAS ', id_municipio: 6 },
		{ id: 537, parroquia: 'JAJI ', id_municipio: 6 },
		{ id: 538, parroquia: 'LA MESA ', id_municipio: 6 },
		{ id: 539, parroquia: 'SAN JOSE DEL SUR ', id_municipio: 6 },
		{ id: 540, parroquia: 'CAPITAL CARACCIOLO PARRA OLMED ', id_municipio: 7 },
		{ id: 541, parroquia: 'FLORENCIO RAMIREZ ', id_municipio: 7 },
		{ id: 542, parroquia: 'CAPITAL CARDENAL QUINTERO ', id_municipio: 8 },
		{ id: 543, parroquia: 'LAS PIEDRAS ', id_municipio: 8 },
		{ id: 544, parroquia: 'CAPITAL GUARAQUE ', id_municipio: 9 },
		{ id: 545, parroquia: 'MESA DE QUINTERO ', id_municipio: 9 },
		{ id: 546, parroquia: 'RIO NEGRO ', id_municipio: 9 },
		{ id: 547, parroquia: 'CAPITAL JULIO CESAR SALAS ', id_municipio: 10 },
		{ id: 548, parroquia: 'PALMIRA ', id_municipio: 10 },
		{ id: 549, parroquia: 'CAPITAL JUSTO BRICEÑO', id_municipio: 14 },
		{ id: 550, parroquia: 'SAN CRISTOBAL DE TORONDOY ', id_municipio: 11 },
		{ id: 551, parroquia: 'ANTONIO SPINETTI DINI ', id_municipio: 12 },
		{ id: 552, parroquia: 'ARIAS ', id_municipio: 12 },
		{ id: 553, parroquia: 'CARACCIOLO PARRA PEREZ ', id_municipio: 12 },
		{ id: 554, parroquia: 'DOMINGO PEÑA', id_municipio: 14 },
		{ id: 555, parroquia: 'EL LLANO ', id_municipio: 12 },
		{ id: 556, parroquia: 'GONZALO PICON FEBRES ', id_municipio: 12 },
		{ id: 557, parroquia: 'JACINTO PLAZA ', id_municipio: 12 },
		{ id: 558, parroquia: 'JUAN RODRIGUEZ SUAREZ ', id_municipio: 12 },
		{ id: 559, parroquia: 'LASSO DE LA VEGA ', id_municipio: 12 },
		{ id: 560, parroquia: 'MARIANO PICON SALAS ', id_municipio: 12 },
		{ id: 561, parroquia: 'MILLA ', id_municipio: 12 },
		{ id: 562, parroquia: 'OSUNA RODRIGUEZ ', id_municipio: 12 },
		{ id: 563, parroquia: 'SAGRARIO ', id_municipio: 12 },
		{ id: 564, parroquia: 'EL MORRO ', id_municipio: 12 },
		{ id: 565, parroquia: 'LOS NEVADOS ', id_municipio: 12 },
		{ id: 566, parroquia: 'CAPITAL MIRANDA ', id_municipio: 13 },
		{ id: 567, parroquia: 'ANDRES ELOY BLANCO ', id_municipio: 13 },
		{ id: 568, parroquia: 'LA VENTA ', id_municipio: 13 },
		{ id: 569, parroquia: 'PIÑA', id_municipio: 14 },
		{ id: 570, parroquia: 'CAPITAL OBISPO RAMOS DE LORA ', id_municipio: 14 },
		{ id: 571, parroquia: 'EL PAUJI ', id_municipio: 14 },
		{ id: 572, parroquia: 'SAN RAFAEL DE ALCAZAR ', id_municipio: 14 },
		{ id: 573, parroquia: 'CAPITAL PADRE NOGUERA ', id_municipio: 15 },
		{ id: 574, parroquia: 'CAPITAL PUEBLO LLANO ', id_municipio: 16 },
		{ id: 575, parroquia: 'CAPITAL RANGEL ', id_municipio: 17 },
		{ id: 576, parroquia: 'CACUTE ', id_municipio: 17 },
		{ id: 577, parroquia: 'LA TOMA ', id_municipio: 17 },
		{ id: 578, parroquia: 'MUCURUBA ', id_municipio: 17 },
		{ id: 579, parroquia: 'SAN RAFAEL ', id_municipio: 17 },
		{ id: 580, parroquia: 'CAPITAL RIVAS DAVILA ', id_municipio: 18 },
		{ id: 581, parroquia: 'GERONIMO MALDONADO ', id_municipio: 18 },
		{ id: 582, parroquia: 'CAPITAL SANTOS MARQUINA ', id_municipio: 19 },
		{ id: 583, parroquia: 'CAPITAL SUCRE ', id_municipio: 20 },
		{ id: 584, parroquia: 'CHIGUARA ', id_municipio: 20 },
		{ id: 585, parroquia: 'ESTANQUEZ ', id_municipio: 20 },
		{ id: 586, parroquia: 'LA TRAMPA ', id_municipio: 20 },
		{ id: 587, parroquia: 'PUEBLO NUEVO DEL SUR ', id_municipio: 20 },
		{ id: 588, parroquia: 'SAN JUAN ', id_municipio: 20 },
		{ id: 589, parroquia: 'EL AMPARO ', id_municipio: 21 },
		{ id: 590, parroquia: 'EL LLANO ', id_municipio: 21 },
		{ id: 591, parroquia: 'SAN FRANCISCO ', id_municipio: 21 },
		{ id: 592, parroquia: 'TOVAR ', id_municipio: 21 },
		{ id: 593, parroquia: 'CAPITAL TULIO FEBRES CORDERO ', id_municipio: 22 },
		{ id: 594, parroquia: 'INDEPENDENCIA ', id_municipio: 22 },
		{ id: 595, parroquia: 'MARIA DE LA C PALACIOS BLANCO ', id_municipio: 22 },
		{ id: 596, parroquia: 'SANTA APOLONIA ', id_municipio: 22 },
		{ id: 597, parroquia: 'CAPITAL ZEA ', id_municipio: 23 },
		{ id: 598, parroquia: 'CAÑO', id_municipio: 14 },
		{ id: 599, parroquia: 'CAUCAGUA ', id_municipio: 177 },
		{ id: 600, parroquia: 'ARAGUITA ', id_municipio: 1 },
		{ id: 601, parroquia: 'AREVALO GONZALEZ ', id_municipio: 1 },
		{ id: 602, parroquia: 'CAPAYA ', id_municipio: 1 },
		{ id: 603, parroquia: 'EL CAFE ', id_municipio: 1 },
		{ id: 604, parroquia: 'MARIZAPA ', id_municipio: 1 },
		{ id: 605, parroquia: 'PANAQUIRE ', id_municipio: 1 },
		{ id: 606, parroquia: 'RIBAS ', id_municipio: 1 },
		{ id: 607, parroquia: 'SAN JOSE DE BARLOVENTO ', id_municipio: 2 },
		{ id: 608, parroquia: 'CUMBO ', id_municipio: 2 },
		{ id: 609, parroquia: 'BARUTA ', id_municipio: 337 },
		{ id: 610, parroquia: 'EL CAFETAL ', id_municipio: 337 },
		{ id: 611, parroquia: 'LAS MINAS DE BARUTA ', id_municipio: 3 },
		{ id: 612, parroquia: 'HIGUEROTE ', id_municipio: 4 },
		{ id: 613, parroquia: 'CURIEPE ', id_municipio: 4 },
		{ id: 614, parroquia: 'TACARIGUA ', id_municipio: 4 },
		{ id: 615, parroquia: 'MAMPORAL ', id_municipio: 5 },
		{ id: 616, parroquia: 'CARRIZAL ', id_municipio: 182 },
		{ id: 617, parroquia: 'CHACAO ', id_municipio: 183 },
		{ id: 618, parroquia: 'CHARALLAVE ', id_municipio: 184 },
		{ id: 619, parroquia: 'LAS BRISAS ', id_municipio: 8 },
		{ id: 620, parroquia: 'EL HATILLO ', id_municipio: 9 },
		{ id: 621, parroquia: 'LOS TEQUES ', id_municipio: 10 },
		{ id: 622, parroquia: 'ALTAGRACIA DE LA MONTAÑA', id_municipio: 7 },
		{ id: 623, parroquia: 'CECILIO ACOSTA ', id_municipio: 186 },
		{ id: 624, parroquia: 'EL JARILLO ', id_municipio: 10 },
		{ id: 625, parroquia: 'PARACOTOS ', id_municipio: 10 },
		{ id: 626, parroquia: 'SAN PEDRO ', id_municipio: 10 },
		{ id: 627, parroquia: 'TACATA ', id_municipio: 10 },
		{ id: 628, parroquia: 'SANTA TERESA DEL TUY ', id_municipio: 11 },
		{ id: 629, parroquia: 'EL CARTANAL ', id_municipio: 11 },
		{ id: 630, parroquia: 'OCUMARE DEL TUY ', id_municipio: 12 },
		{ id: 631, parroquia: 'LA DEMOCRACIA ', id_municipio: 12 },
		{ id: 632, parroquia: 'SANTA BARBARA ', id_municipio: 12 },
		{ id: 633, parroquia: 'SAN ANTONIO DE LOS ALTOS ', id_municipio: 13 },
		{ id: 634, parroquia: 'RIO CHICO ', id_municipio: 14 },
		{ id: 635, parroquia: 'EL GUAPO ', id_municipio: 14 },
		{ id: 636, parroquia: 'TACARIGUA DE LA LAGUNA ', id_municipio: 14 },
		{ id: 637, parroquia: 'PAPARO ', id_municipio: 14 },
		{ id: 638, parroquia: 'SAN FERNANDO DEL GUAPO ', id_municipio: 14 },
		{ id: 639, parroquia: 'SANTA LUCIA ', id_municipio: 15 },
		{ id: 640, parroquia: 'CUPIRA ', id_municipio: 16 },
		{ id: 641, parroquia: 'MACHURUCUTO ', id_municipio: 16 },
		{ id: 642, parroquia: 'GUARENAS ', id_municipio: 17 },
		{ id: 643, parroquia: 'SAN FRANCISCO DE YARE ', id_municipio: 18 },
		{ id: 644, parroquia: 'SAN ANTONIO DE YARE ', id_municipio: 18 },
		{ id: 645, parroquia: 'PETARE ', id_municipio: 19 },
		{ id: 646, parroquia: 'CAUCAGUITA ', id_municipio: 19 },
		{ id: 647, parroquia: 'FILA DE MARICHES ', id_municipio: 19 },
		{ id: 648, parroquia: 'LA DOLORITA ', id_municipio: 19 },
		{ id: 649, parroquia: 'LEONCIO MARTINEZ ', id_municipio: 19 },
		{ id: 650, parroquia: 'CUA ', id_municipio: 20 },
		{ id: 651, parroquia: 'NUEVA CUA ', id_municipio: 20 },
		{ id: 652, parroquia: 'GUATIRE ', id_municipio: 21 },
		{ id: 653, parroquia: 'BOLIVAR ', id_municipio: 21 },
		{ id: 654, parroquia: 'CAPITAL ACOSTA ', id_municipio: 1 },
		{ id: 655, parroquia: 'SAN FRANCISCO ', id_municipio: 1 },
		{ id: 656, parroquia: 'CAPITAL AGUASAY ', id_municipio: 2 },
		{ id: 657, parroquia: 'CAPITAL BOLIVAR ', id_municipio: 3 },
		{ id: 658, parroquia: 'CAPITAL CARIPE ', id_municipio: 4 },
		{ id: 659, parroquia: 'EL GUACHARO ', id_municipio: 4 },
		{ id: 660, parroquia: 'LA GUANOTA ', id_municipio: 4 },
		{ id: 661, parroquia: 'SABANA DE PIEDRA ', id_municipio: 4 },
		{ id: 662, parroquia: 'SAN AGUSTIN ', id_municipio: 4 },
		{ id: 663, parroquia: 'TERESEN ', id_municipio: 4 },
		{ id: 664, parroquia: 'CAPITAL CEDEÑA', id_municipio: 16 },
		{ id: 665, parroquia: 'AREO ', id_municipio: 5 },
		{ id: 666, parroquia: 'SAN FELIX ', id_municipio: 5 },
		{ id: 667, parroquia: 'VIENTO FRESCO ', id_municipio: 5 },
		{ id: 668, parroquia: 'CAPITAL EZEQUIEL ZAMORA ', id_municipio: 6 },
		{ id: 669, parroquia: 'EL TEJERO ', id_municipio: 6 },
		{ id: 670, parroquia: 'CAPITAL LIBERTADOR ', id_municipio: 7 },
		{ id: 671, parroquia: 'CHAGUARAMAS ', id_municipio: 7 },
		{ id: 672, parroquia: 'LA PETROLEA ', id_municipio: 7 },
		{ id: 673, parroquia: 'TABASCA ', id_municipio: 7 },
		{ id: 674, parroquia: 'CAPITAL MATURIN ', id_municipio: 8 },
		{ id: 675, parroquia: 'ALTO DE LOS GODOS ', id_municipio: 8 },
		{ id: 676, parroquia: 'BOQUERON ', id_municipio: 8 },
		{ id: 677, parroquia: 'LAS COCUIZAS ', id_municipio: 8 },
		{ id: 678, parroquia: 'SAN SIMON ', id_municipio: 8 },
		{ id: 679, parroquia: 'SANTA CRUZ ', id_municipio: 8 },
		{ id: 680, parroquia: 'EL COROZO ', id_municipio: 8 },
		{ id: 681, parroquia: 'EL FURRIAL ', id_municipio: 8 },
		{ id: 682, parroquia: 'JUSEPIN ', id_municipio: 8 },
		{ id: 683, parroquia: 'LA PICA ', id_municipio: 8 },
		{ id: 684, parroquia: 'SAN VICENTE ', id_municipio: 8 },
		{ id: 685, parroquia: 'CAPITAL PIAR ', id_municipio: 9 },
		{ id: 686, parroquia: 'APARICIO ', id_municipio: 9 },
		{ id: 687, parroquia: 'CHAGUARAMAL ', id_municipio: 9 },
		{ id: 688, parroquia: 'EL PINTO ', id_municipio: 9 },
		{ id: 689, parroquia: 'GUANAGUANA ', id_municipio: 9 },
		{ id: 690, parroquia: 'LA TOSCANA ', id_municipio: 9 },
		{ id: 691, parroquia: 'TAGUAYA ', id_municipio: 9 },
		{ id: 692, parroquia: 'CAPITAL PUNCERES ', id_municipio: 10 },
		{ id: 693, parroquia: 'CACHIPO ', id_municipio: 10 },
		{ id: 694, parroquia: 'CAPITAL SANTA BARBARA ', id_municipio: 11 },
		{ id: 695, parroquia: 'CAPITAL SOTILLO ', id_municipio: 12 },
		{ id: 696, parroquia: 'LOS BARRANCOS DE FAJARDO ', id_municipio: 12 },
		{ id: 697, parroquia: 'CAPITAL URACOA ', id_municipio: 13 },
		{ id: 698, parroquia: 'CAPITAL ANTOLIN DEL CAMPO ', id_municipio: 1 },
		{ id: 699, parroquia: 'CAPITAL ARISMENDI ', id_municipio: 2 },
		{ id: 700, parroquia: 'CAPITAL DIAZ ', id_municipio: 3 },
		{ id: 701, parroquia: 'ZABALA ', id_municipio: 3 },
		{ id: 702, parroquia: 'CAPITAL GARCIA ', id_municipio: 4 },
		{ id: 703, parroquia: 'FRANCISCO FAJARDO ', id_municipio: 4 },
		{ id: 704, parroquia: 'CAPITAL GOMEZ ', id_municipio: 5 },
		{ id: 705, parroquia: 'BOLIVAR ', id_municipio: 5 },
		{ id: 706, parroquia: 'GUEVARA ', id_municipio: 5 },
		{ id: 707, parroquia: 'MATASIETE ', id_municipio: 5 },
		{ id: 708, parroquia: 'SUCRE ', id_municipio: 5 },
		{ id: 709, parroquia: 'CAPITAL MANEIRO ', id_municipio: 6 },
		{ id: 710, parroquia: 'AGUIRRE ', id_municipio: 6 },
		{ id: 711, parroquia: 'CAPITAL MARCANO ', id_municipio: 7 },
		{ id: 712, parroquia: 'ADRIAN ', id_municipio: 7 },
		{ id: 713, parroquia: 'CAPITAL MARIÑO', id_municipio: 17 },
		{ id: 714, parroquia: 'CAPITAL PENINSULA DE MACANAO ', id_municipio: 9 },
		{ id: 715, parroquia: 'SAN FRANCISCO ', id_municipio: 9 },
		{ id: 716, parroquia: 'CAPITAL TUBORES ', id_municipio: 10 },
		{ id: 717, parroquia: 'LOS BARALES ', id_municipio: 10 },
		{ id: 718, parroquia: 'CAPITAL VILLALBA ', id_municipio: 11 },
		{ id: 719, parroquia: 'VICENTE FUENTES ', id_municipio: 11 },
		{ id: 720, parroquia: 'CAPITAL AGUA BLANCA ', id_municipio: 1 },
		{ id: 721, parroquia: 'CAPITAL ARAURE ', id_municipio: 2 },
		{ id: 722, parroquia: 'RIO ACARIGUA ', id_municipio: 2 },
		{ id: 723, parroquia: 'CAPITAL ESTELLER ', id_municipio: 3 },
		{ id: 724, parroquia: 'UVERAL ', id_municipio: 3 },
		{ id: 725, parroquia: 'CAPITAL GUANARE ', id_municipio: 4 },
		{ id: 726, parroquia: 'CORDOBA ', id_municipio: 4 },
		{ id: 727, parroquia: 'SAN JOSE DE LA MONTAÑA', id_municipio: 18 },
		{ id: 728, parroquia: 'SAN JUAN DE GUANAGUANARE ', id_municipio: 4 },
		{ id: 729, parroquia: 'VIRGEN DE LA COROMOTO ', id_municipio: 4 },
		{ id: 730, parroquia: 'CAPITAL GUANARITO ', id_municipio: 5 },
		{ id: 731, parroquia: 'TRINIDAD DE LA CAPILLA ', id_municipio: 5 },
		{ id: 732, parroquia: 'DIVINA PASTORA ', id_municipio: 5 },
		{ id: 733, parroquia: 'CAPITAL MONS. JOSE V. DE UNDA ', id_municipio: 6 },
		{ id: 734, parroquia: 'PEÑA', id_municipio: 18 },
		{ id: 735, parroquia: 'CAPITAL OSPINO ', id_municipio: 7 },
		{ id: 736, parroquia: 'APARICION ', id_municipio: 7 },
		{ id: 737, parroquia: 'LA ESTACION ', id_municipio: 7 },
		{ id: 738, parroquia: 'CAPITAL PAEZ ', id_municipio: 8 },
		{ id: 739, parroquia: 'PAYARA ', id_municipio: 8 },
		{ id: 740, parroquia: 'PIMPINELA ', id_municipio: 8 },
		{ id: 741, parroquia: 'RAMON PERAZA ', id_municipio: 8 },
		{ id: 742, parroquia: 'CAPITAL PAPELON ', id_municipio: 9 },
		{ id: 743, parroquia: 'CAÑA', id_municipio: 18 },
		{ id: 744, parroquia: 'CAPITAL S GENARO DE BOCONOITO ', id_municipio: 10 },
		{ id: 745, parroquia: 'ANTOLIN TOVAR ', id_municipio: 10 },
		{ id: 746, parroquia: 'CAPITAL SAN RAFAEL DE ONOTO ', id_municipio: 11 },
		{ id: 747, parroquia: 'SANTA FE ', id_municipio: 11 },
		{ id: 748, parroquia: 'THERMO MORLES ', id_municipio: 11 },
		{ id: 749, parroquia: 'CAPITAL SANTA ROSALIA ', id_municipio: 12 },
		{ id: 750, parroquia: 'FLORIDA ', id_municipio: 12 },
		{ id: 751, parroquia: 'CAPITAL S GERONIM. DE GUAYABAL ', id_municipio: 13 },
		{ id: 752, parroquia: 'CONCEPCION ', id_municipio: 13 },
		{ id: 753, parroquia: 'SAN RAFAEL DE PALO ALZADO ', id_municipio: 13 },
		{ id: 754, parroquia: 'UVENCIO ANTONIO VELASQUEZ ', id_municipio: 13 },
		{ id: 755, parroquia: 'SAN JOSE DE SAGUAZ ', id_municipio: 13 },
		{ id: 756, parroquia: 'VILLA ROSA ', id_municipio: 13 },
		{ id: 757, parroquia: 'CAPITAL TURUN ', id_municipio: 14 },
		{ id: 758, parroquia: 'CUPIRA ', id_municipio: 14 },
		{ id: 759, parroquia: 'SANTA CRUZ ', id_municipio: 14 },
		{ id: 760, parroquia: 'SAN ISIDRO LABRADOR ', id_municipio: 14 },
		{ id: 761, parroquia: 'MAIQUETIA ', id_municipio: 1 },
		{ id: 762, parroquia: 'ROMULO GALLEGOS ', id_municipio: 1 },
		{ id: 763, parroquia: 'SAN JOSE DE AEROCUAR ', id_municipio: 2 },
		{ id: 764, parroquia: 'TAVERA ACOSTA ', id_municipio: 2 },
		{ id: 765, parroquia: 'RIO CARIBE ', id_municipio: 3 },
		{ id: 766, parroquia: 'ANTONIO JOSE DE SUCRE ', id_municipio: 3 },
		{ id: 767, parroquia: 'EL MORRO DE PUERTO SANTO ', id_municipio: 3 },
		{ id: 768, parroquia: 'PUERTO SANTO ', id_municipio: 3 },
		{ id: 769, parroquia: 'SAN JUAN DE LAS GALDONAS ', id_municipio: 3 },
		{ id: 770, parroquia: 'EL PILAR ', id_municipio: 4 },
		{ id: 771, parroquia: 'EL RINCON ', id_municipio: 4 },
		{ id: 772, parroquia: 'GENERAL FRANCISCO A. VASQUEZ ', id_municipio: 4 },
		{ id: 773, parroquia: 'GUARAUNOS ', id_municipio: 4 },
		{ id: 774, parroquia: 'TUNAPUICITO ', id_municipio: 4 },
		{ id: 775, parroquia: 'UNION ', id_municipio: 4 },
		{ id: 776, parroquia: 'BOLIVAR ', id_municipio: 5 },
		{ id: 777, parroquia: 'MACARAPANA ', id_municipio: 5 },
		{ id: 778, parroquia: 'SANTA CATALINA ', id_municipio: 5 },
		{ id: 779, parroquia: 'SANTA ROSA ', id_municipio: 5 },
		{ id: 780, parroquia: 'SANTA TERESA ', id_municipio: 5 },
		{ id: 781, parroquia: 'CAPITAL BOLIVAR ', id_municipio: 6 },
		{ id: 782, parroquia: 'YAGUARAPARO ', id_municipio: 7 },
		{ id: 783, parroquia: 'EL PAUJIL ', id_municipio: 7 },
		{ id: 784, parroquia: 'LIBERTAD ', id_municipio: 7 },
		{ id: 785, parroquia: 'ARAYA ', id_municipio: 8 },
		{ id: 786, parroquia: 'CHACOPATA ', id_municipio: 8 },
		{ id: 787, parroquia: 'MANICUARE ', id_municipio: 8 },
		{ id: 788, parroquia: 'TUNAPUY ', id_municipio: 9 },
		{ id: 789, parroquia: 'CAMPO ELIAS ', id_municipio: 9 },
		{ id: 790, parroquia: 'IRAPA ', id_municipio: 10 },
		{ id: 791, parroquia: 'CAMPO CLARO ', id_municipio: 10 },
		{ id: 792, parroquia: 'MARABAL ', id_municipio: 10 },
		{ id: 793, parroquia: 'RIO CARIBE ', id_municipio: 10 },
		{ id: 794, parroquia: 'SORO ', id_municipio: 10 },
		{ id: 795, parroquia: 'CAPITAL MEJIA ', id_municipio: 11 },
		{ id: 796, parroquia: 'CUMANACOA ', id_municipio: 12 },
		{ id: 797, parroquia: 'ARENAS ', id_municipio: 12 },
		{ id: 798, parroquia: 'ARICAGUA ', id_municipio: 12 },
		{ id: 799, parroquia: 'COCOLLAR ', id_municipio: 12 },
		{ id: 800, parroquia: 'SAN FERNANDO ', id_municipio: 12 },
		{ id: 801, parroquia: 'SAN LORENZO ', id_municipio: 12 },
		{ id: 802, parroquia: 'VILLA FRONTADO (M. DE CARIACO) ', id_municipio: 13 },
		{ id: 803, parroquia: 'CARACCIOLO PARRA PUREZ ', id_municipio: 13 },
		{ id: 804, parroquia: 'RENDON ', id_municipio: 13 },
		{ id: 805, parroquia: 'SAN SEBASTIAN ', id_municipio: 13 },
		{ id: 806, parroquia: 'SANTA BARBARA ', id_municipio: 13 },
		{ id: 807, parroquia: 'ALTAGRACIA ', id_municipio: 14 },
		{ id: 808, parroquia: 'AYACUCHO ', id_municipio: 14 },
		{ id: 809, parroquia: 'SANTA INES ', id_municipio: 14 },
		{ id: 810, parroquia: 'VALENTIN VALIENTE ', id_municipio: 14 },
		{ id: 811, parroquia: 'SAN JUAN ', id_municipio: 14 },
		{ id: 812, parroquia: 'RAUL LEONI ', id_municipio: 14 },
		{ id: 813, parroquia: 'SANTA FE ', id_municipio: 14 },
		{ id: 814, parroquia: 'GUIRIA ', id_municipio: 15 },
		{ id: 815, parroquia: 'BIDEAU ', id_municipio: 15 },
		{ id: 816, parroquia: 'CRISTOBAL COLON ', id_municipio: 15 },
		{ id: 817, parroquia: 'PUNTA DE PIEDRAS ', id_municipio: 15 },
		{ id: 818, parroquia: 'CAPITAL ANDRES BELLO ', id_municipio: 1 },
		{ id: 819, parroquia: 'CAMPO ELIAS ', id_municipio: 2 },
		{ id: 820, parroquia: 'AYACUCHO ', id_municipio: 3 },
		{ id: 821, parroquia: 'RIVAS BERTI ', id_municipio: 3 },
		{ id: 822, parroquia: 'SAN PEDRO DEL RIO ', id_municipio: 3 },
		{ id: 823, parroquia: 'BOLIVAR ', id_municipio: 4 },
		{ id: 824, parroquia: 'PALOTAL ', id_municipio: 4 },
		{ id: 825, parroquia: 'JUAN VICENTE GOMEZ ', id_municipio: 4 },
		{ id: 826, parroquia: 'ISAIAS MEDINA ANGARITA ', id_municipio: 4 },
		{ id: 827, parroquia: 'CARDENAS ', id_municipio: 5 },
		{ id: 828, parroquia: 'AMENODORO RANGEL LAMUS ', id_municipio: 5 },
		{ id: 829, parroquia: 'LA FLORIDA ', id_municipio: 5 },
		{ id: 830, parroquia: 'CAPITAL CORDOBA ', id_municipio: 6 },
		{ id: 831, parroquia: 'FERNANDEZ FEO ', id_municipio: 7 },
		{ id: 832, parroquia: 'ALBERTO ADRIANI ', id_municipio: 7 },
		{ id: 833, parroquia: 'SANTO DOMINGO ', id_municipio: 7 },
		{ id: 834, parroquia: 'CAPITAL BOLIVAR ', id_municipio: 8 },
		{ id: 835, parroquia: 'CAPITAL GARCIA DE HEVIA ', id_municipio: 9 },
		{ id: 836, parroquia: 'BOCA DE GRITA ', id_municipio: 9 },
		{ id: 837, parroquia: 'JOSE ANTONIO PAEZ ', id_municipio: 9 },
		{ id: 838, parroquia: 'CAPITAL GUASIMOS ', id_municipio: 10 },
		{ id: 839, parroquia: 'INDEPENDENCIA ', id_municipio: 11 },
		{ id: 840, parroquia: 'JUAN GERMAN ROSCIO ', id_municipio: 11 },
		{ id: 841, parroquia: 'ROMAN CARDENAS ', id_municipio: 11 },
		{ id: 842, parroquia: 'JAUREGUI ', id_municipio: 12 },
		{ id: 843, parroquia: 'EMILIO CONSTANTINO GUERRERO ', id_municipio: 12 },
		{ id: 844, parroquia: 'MONSEÑOR', id_municipio: 20 },
		{ id: 845, parroquia: 'CAPITAL JOSE MARIA VARGAS ', id_municipio: 13 },
		{ id: 846, parroquia: 'JUNIN ', id_municipio: 14 },
		{ id: 847, parroquia: 'LA PETROLEA ', id_municipio: 14 },
		{ id: 848, parroquia: 'QUINIMARI ', id_municipio: 14 },
		{ id: 849, parroquia: 'BRAMON ', id_municipio: 14 },
		{ id: 850, parroquia: 'LIBERTAD ', id_municipio: 15 },
		{ id: 851, parroquia: 'CIPRIANO CASTRO ', id_municipio: 15 },
		{ id: 852, parroquia: 'MANUEL FELIPE RUGELES ', id_municipio: 15 },
		{ id: 853, parroquia: 'LIBERTADOR ', id_municipio: 16 },
		{ id: 854, parroquia: 'EMETERIO OCHOA ', id_municipio: 16 },
		{ id: 855, parroquia: 'DORADAS ', id_municipio: 16 },
		{ id: 856, parroquia: 'SAN JOAQUIN DE NAVAY ', id_municipio: 16 },
		{ id: 857, parroquia: 'LOBATERA ', id_municipio: 17 },
		{ id: 858, parroquia: 'CONSTITUCION ', id_municipio: 17 },
		{ id: 859, parroquia: 'CAPITAL MICHELENA ', id_municipio: 18 },
		{ id: 860, parroquia: 'PANAMERICANO ', id_municipio: 19 },
		{ id: 861, parroquia: 'LA PALMITA ', id_municipio: 19 },
		{ id: 862, parroquia: 'PEDRO MARIA UREÑA', id_municipio: 20 },
		{ id: 863, parroquia: 'NUEVA ARCADIA ', id_municipio: 20 },
		{ id: 864, parroquia: 'CAPITAL RAFAEL URDANETA ', id_municipio: 21 },
		{ id: 865, parroquia: 'SAMUEL DARIO MALDONADO ', id_municipio: 22 },
		{ id: 866, parroquia: 'BOCONO ', id_municipio: 22 },
		{ id: 867, parroquia: 'HERNANDEZ ', id_municipio: 22 },
		{ id: 868, parroquia: 'LA CONCORDIA ', id_municipio: 23 },
		{ id: 869, parroquia: 'PEDRO MARIA MORANTES ', id_municipio: 23 },
		{ id: 870, parroquia: 'SAN JUAN BAUTISTA ', id_municipio: 23 },
		{ id: 871, parroquia: 'SAN SEBASTIAN ', id_municipio: 23 },
		{ id: 872, parroquia: 'CARDENAS ', id_municipio: 23 },
		{ id: 873, parroquia: 'CAPITAL SEBORUCO ', id_municipio: 24 },
		{ id: 874, parroquia: 'CAPITAL SIMON RODRIGUEZ ', id_municipio: 25 },
		{ id: 875, parroquia: 'SUCRE ', id_municipio: 26 },
		{ id: 876, parroquia: 'ELEAZAR LOPEZ CONTRERAS ', id_municipio: 26 },
		{ id: 877, parroquia: 'SAN PABLO ', id_municipio: 26 },
		{ id: 878, parroquia: 'CAPITAL TORBES ', id_municipio: 27 },
		{ id: 879, parroquia: 'CAPITAL URIBANTE ', id_municipio: 28 },
		{ id: 880, parroquia: 'CARDENAS ', id_municipio: 28 },
		{ id: 881, parroquia: 'JOSE VIDAL MARCANO ', id_municipio: 28 },
		{ id: 882, parroquia: 'POTOSI ', id_municipio: 28 },
		{ id: 883, parroquia: 'CAPITAL SAN JUDAS TADEO ', id_municipio: 29 },
		{ id: 884, parroquia: 'SANTA ISABEL ', id_municipio: 1 },
		{ id: 885, parroquia: 'ARAGUANEY ', id_municipio: 1 },
		{ id: 886, parroquia: 'EL JAGUITO ', id_municipio: 1 },
		{ id: 887, parroquia: 'JUAN MILLAN ', id_municipio: 1 },
		{ id: 888, parroquia: 'BOCONO ', id_municipio: 281 },
		{ id: 889, parroquia: 'EL CARMEN ', id_municipio: 2 },
		{ id: 890, parroquia: 'MESA BOLIVAR ', id_municipio: 2 },
		{ id: 891, parroquia: 'AYACUCHO ', id_municipio: 2 },
		{ id: 892, parroquia: 'BURBUSAY ', id_municipio: 2 },
		{ id: 893, parroquia: 'GENERAL RIVAS ', id_municipio: 2 },
		{ id: 894, parroquia: 'GUARAMACAL ', id_municipio: 2 },
		{ id: 895, parroquia: 'VEGA DE GUARAMACAL ', id_municipio: 2 },
		{ id: 896, parroquia: 'MONSEÑOR', id_municipio: 21 },
		{ id: 897, parroquia: 'RAFAEL RANGEL ', id_municipio: 2 },
		{ id: 898, parroquia: 'SAN MIGUEL ', id_municipio: 2 },
		{ id: 899, parroquia: 'SAN JOSE ', id_municipio: 2 },
		{ id: 900, parroquia: 'SABANA GRANDE ', id_municipio: 3 },
		{ id: 901, parroquia: 'CHEREGUE ', id_municipio: 3 },
		{ id: 902, parroquia: 'GRANADOS ', id_municipio: 3 },
		{ id: 903, parroquia: 'CASTAÑO', id_municipio: 21 },
		{ id: 904, parroquia: 'ARNOLDO GABALDON ', id_municipio: 4 },
		{ id: 905, parroquia: 'BOLIVIA ', id_municipio: 4 },
		{ id: 906, parroquia: 'CARRILLO ', id_municipio: 4 },
		{ id: 907, parroquia: 'CEGARRA ', id_municipio: 4 },
		{ id: 908, parroquia: 'MANUEL SALVADOR ULLOA ', id_municipio: 4 },
		{ id: 909, parroquia: 'SAN JOSE ', id_municipio: 4 },
		{ id: 910, parroquia: 'CARACHE ', id_municipio: 5 },
		{ id: 911, parroquia: 'CUICAS ', id_municipio: 5 },
		{ id: 912, parroquia: 'LA CONCEPCION ', id_municipio: 5 },
		{ id: 913, parroquia: 'PANAMERICANA ', id_municipio: 5 },
		{ id: 914, parroquia: 'SANTA CRUZ ', id_municipio: 5 },
		{ id: 915, parroquia: 'ESCUQUE ', id_municipio: 6 },
		{ id: 916, parroquia: 'LA UNION ', id_municipio: 6 },
		{ id: 917, parroquia: 'SABANA LIBRE ', id_municipio: 6 },
		{ id: 918, parroquia: 'SANTA RITA ', id_municipio: 6 },
		{ id: 919, parroquia: 'EL SOCORRO ', id_municipio: 7 },
		{ id: 920, parroquia: 'ANTONIO JOSE DE SUCRE ', id_municipio: 7 },
		{ id: 921, parroquia: 'LOS CAPRICHOS ', id_municipio: 7 },
		{ id: 922, parroquia: 'CAMPO ELIAS ', id_municipio: 8 },
		{ id: 923, parroquia: 'ARNOLDO GABALDON ', id_municipio: 8 },
		{ id: 924, parroquia: 'SANTA APOLONIA ', id_municipio: 9 },
		{ id: 925, parroquia: 'EL JAGUITO ', id_municipio: 9 },
		{ id: 926, parroquia: 'LA CEIBA ', id_municipio: 9 },
		{ id: 927, parroquia: 'TRES DE FEBRERO ', id_municipio: 9 },
		{ id: 928, parroquia: 'EL DIVIDIVE ', id_municipio: 10 },
		{ id: 929, parroquia: 'AGUA SANTA ', id_municipio: 10 },
		{ id: 930, parroquia: 'AGUA CALIENTE ', id_municipio: 10 },
		{ id: 931, parroquia: 'EL CENIZO ', id_municipio: 10 },
		{ id: 932, parroquia: 'VALERITA ', id_municipio: 10 },
		{ id: 933, parroquia: 'MONTE CARMELO ', id_municipio: 11 },
		{ id: 934, parroquia: 'BUENA VISTA ', id_municipio: 11 },
		{ id: 935, parroquia: 'SANTA MARIA DEL HORCON ', id_municipio: 11 },
		{ id: 936, parroquia: 'MOTATAN ', id_municipio: 12 },
		{ id: 937, parroquia: 'EL BAÑO', id_municipio: 21 },
		{ id: 938, parroquia: 'JALISCO ', id_municipio: 12 },
		{ id: 939, parroquia: 'PAMPAN ', id_municipio: 13 },
		{ id: 940, parroquia: 'FLOR DE PATRIA ', id_municipio: 13 },
		{ id: 941, parroquia: 'LA PAZ ', id_municipio: 13 },
		{ id: 942, parroquia: 'SANTA ANA ', id_municipio: 13 },
		{ id: 943, parroquia: 'PAMPANITO ', id_municipio: 14 },
		{ id: 944, parroquia: 'LA CONCEPCION ', id_municipio: 14 },
		{ id: 945, parroquia: 'PAMPANITO II ', id_municipio: 14 },
		{ id: 946, parroquia: 'BETIJOQUE ', id_municipio: 15 },
		{ id: 947, parroquia: 'LA CONCEPCION ', id_municipio: 15 },
		{ id: 948, parroquia: 'LOS CEDROS ', id_municipio: 15 },
		{ id: 949, parroquia: 'JOSE GREGORIO HERNANDEZ ', id_municipio: 15 },
		{ id: 950, parroquia: 'CARVAJAL ', id_municipio: 16 },
		{ id: 951, parroquia: 'ANTONIO NICOLAS BRICEÑO', id_municipio: 21 },
		{ id: 952, parroquia: 'CAMPO ALEGRE ', id_municipio: 16 },
		{ id: 953, parroquia: 'JOSE LEONARDO SUAREZ ', id_municipio: 16 },
		{ id: 954, parroquia: 'SABANA DE MENDOZA ', id_municipio: 17 },
		{ id: 955, parroquia: 'EL PARAISO ', id_municipio: 17 },
		{ id: 956, parroquia: 'JUNIN ', id_municipio: 17 },
		{ id: 957, parroquia: 'VALMORE RODRIGUEZ ', id_municipio: 17 },
		{ id: 958, parroquia: 'ANDRES LINARES ', id_municipio: 18 },
		{ id: 959, parroquia: 'CHIQUINQUIRA ', id_municipio: 18 },
		{ id: 960, parroquia: 'CRISTOBAL MENDOZA ', id_municipio: 18 },
		{ id: 961, parroquia: 'CRUZ CARRILLO ', id_municipio: 18 },
		{ id: 962, parroquia: 'MATRIZ ', id_municipio: 18 },
		{ id: 963, parroquia: 'MONSEÑOR', id_municipio: 21 },
		{ id: 964, parroquia: 'TRES ESQUINAS ', id_municipio: 18 },
		{ id: 965, parroquia: 'LA QUEBRADA ', id_municipio: 19 },
		{ id: 966, parroquia: 'CABIMBU ', id_municipio: 19 },
		{ id: 967, parroquia: 'JAJO ', id_municipio: 19 },
		{ id: 968, parroquia: 'LA MESA ', id_municipio: 19 },
		{ id: 969, parroquia: 'SANTIAGO ', id_municipio: 19 },
		{ id: 970, parroquia: 'TUÑA', id_municipio: 21 },
		{ id: 971, parroquia: 'JUAN IGNACIO MONTILLA ', id_municipio: 20 },
		{ id: 972, parroquia: 'LA BEATRIZ ', id_municipio: 20 },
		{ id: 973, parroquia: 'MERCEDES DIAZ ', id_municipio: 20 },
		{ id: 974, parroquia: 'SAN LUIS ', id_municipio: 20 },
		{ id: 975, parroquia: 'LA PUERTA ', id_municipio: 20 },
		{ id: 976, parroquia: 'MENDOZA ', id_municipio: 20 },
		{ id: 977, parroquia: 'CAPITAL ARISTIDES BASTIDAS ', id_municipio: 1 },
		{ id: 978, parroquia: 'CAPITAL BOLIVAR ', id_municipio: 2 },
		{ id: 979, parroquia: 'CAPITAL BRUZUAL ', id_municipio: 3 },
		{ id: 980, parroquia: 'CAMPO ELIAS ', id_municipio: 3 },
		{ id: 981, parroquia: 'CAPITAL COCOROTE ', id_municipio: 4 },
		{ id: 982, parroquia: 'CAPITAL INDEPENDENCIA ', id_municipio: 5 },
		{ id: 983, parroquia: 'CAPITAL JOSE ANTONIO PAEZ ', id_municipio: 6 },
		{ id: 984, parroquia: 'CAPITAL LA TRINIDAD ', id_municipio: 7 },
		{ id: 985, parroquia: 'CAPITAL MANUEL MONGE ', id_municipio: 8 },
		{ id: 986, parroquia: 'CAPITAL NIRGUA ', id_municipio: 9 },
		{ id: 987, parroquia: 'SALOM ', id_municipio: 9 },
		{ id: 988, parroquia: 'TEMERLA ', id_municipio: 9 },
		{ id: 989, parroquia: 'CAPITAL PEÑA', id_municipio: 22 },
		{ id: 990, parroquia: 'SAN ANDRES ', id_municipio: 10 },
		{ id: 991, parroquia: 'CAPITAL SAN FELIPE ', id_municipio: 11 },
		{ id: 992, parroquia: 'ALBARICO ', id_municipio: 11 },
		{ id: 993, parroquia: 'SAN JAVIER ', id_municipio: 11 },
		{ id: 994, parroquia: 'CAPITAL SUCRE ', id_municipio: 12 },
		{ id: 995, parroquia: 'CAPITAL URACHICHE ', id_municipio: 13 },
		{ id: 996, parroquia: 'CAPITAL VEROES ', id_municipio: 14 },
		{ id: 997, parroquia: 'EL GUAYABO ', id_municipio: 14 },
		{ id: 998, parroquia: 'ISLA DE TOAS ', id_municipio: 1 },
		{ id: 999, parroquia: 'MONAGAS ', id_municipio: 1 },
		{ id: 1000, parroquia: 'SAN TIMOTEO ', id_municipio: 2 },
		{ id: 1001, parroquia: 'GENERAL URDANETA ', id_municipio: 2 },
		{ id: 1002, parroquia: 'LIBERTADOR ', id_municipio: 2 },
		{ id: 1003, parroquia: 'MANUEL GUANIPA MATOS ', id_municipio: 2 },
		{ id: 1004, parroquia: 'MARCELINO BRICEÑO', id_municipio: 23 },
		{ id: 1005, parroquia: 'PUEBLO NUEVO ', id_municipio: 2 },
		{ id: 1006, parroquia: 'AMBROSIO ', id_municipio: 3 },
		{ id: 1007, parroquia: 'CARMEN HERRERA ', id_municipio: 3 },
		{ id: 1008, parroquia: 'GERMAN RIOS LINARES ', id_municipio: 3 },
		{ id: 1009, parroquia: 'LA ROSA ', id_municipio: 3 },
		{ id: 1010, parroquia: 'JORGE HERNANDEZ ', id_municipio: 3 },
		{ id: 1011, parroquia: 'ROMULO BETANCOURT ', id_municipio: 3 },
		{ id: 1012, parroquia: 'SAN BENITO ', id_municipio: 3 },
		{ id: 1013, parroquia: 'ARISTIDES CALVANI ', id_municipio: 3 },
		{ id: 1014, parroquia: 'PUNTA GORDA ', id_municipio: 3 },
		{ id: 1015, parroquia: 'ENCONTRADOS ', id_municipio: 4 },
		{ id: 1016, parroquia: 'UDON PEREZ ', id_municipio: 4 },
		{ id: 1017, parroquia: 'SAN CARLOS DEL ZULIA ', id_municipio: 5 },
		{ id: 1018, parroquia: 'MORALITO ', id_municipio: 5 },
		{ id: 1019, parroquia: 'SANTA BARBARA ', id_municipio: 5 },
		{ id: 1020, parroquia: 'SANTA CRUZ DEL ZULIA ', id_municipio: 5 },
		{ id: 1021, parroquia: 'URRIBARRI ', id_municipio: 5 },
		{ id: 1022, parroquia: 'SIMON RODRIGUEZ ', id_municipio: 6 },
		{ id: 1023, parroquia: 'CARLOS QUEVEDO ', id_municipio: 6 },
		{ id: 1024, parroquia: 'FRANCISCO JAVIER PULGAR ', id_municipio: 6 },
		{ id: 1025, parroquia: 'LA CONCEPCION ', id_municipio: 7 },
		{ id: 1026, parroquia: 'JOSE RAMON YEPES ', id_municipio: 7 },
		{ id: 1027, parroquia: 'MARIANO PARRA LEON ', id_municipio: 7 },
		{ id: 1028, parroquia: 'SAN JOSE ', id_municipio: 7 },
		{ id: 1029, parroquia: 'JESUS MARIA SEMPRUN ', id_municipio: 8 },
		{ id: 1030, parroquia: 'BARI ', id_municipio: 8 },
		{ id: 1031, parroquia: 'CONCEPCION ', id_municipio: 9 },
		{ id: 1032, parroquia: 'ANDRES BELLO ', id_municipio: 9 },
		{ id: 1033, parroquia: 'CHIQUINQUIRA ', id_municipio: 9 },
		{ id: 1034, parroquia: 'EL CARMELO ', id_municipio: 9 },
		{ id: 1035, parroquia: 'POTRERITOS ', id_municipio: 9 },
		{ id: 1036, parroquia: 'ALONSO DE OJEDA ', id_municipio: 10 },
		{ id: 1037, parroquia: 'LIBERTAD ', id_municipio: 10 },
		{ id: 1038, parroquia: 'CAMPO LARA ', id_municipio: 10 },
		{ id: 1039, parroquia: 'ELEAZAR LOPEZ CONTRERAS ', id_municipio: 10 },
		{ id: 1040, parroquia: 'URBANA SAN JOAQUIN ', id_municipio: 10 },
		{ id: 1041, parroquia: 'LIBERTAD ', id_municipio: 11 },
		{ id: 1042, parroquia: 'BARTOLOME DE LAS CASAS ', id_municipio: 11 },
		{ id: 1043, parroquia: 'RIO NEGRO ', id_municipio: 11 },
		{ id: 1044, parroquia: 'SAN JOSE DE PERIJA ', id_municipio: 11 },
		{ id: 1045, parroquia: 'SAN RAFAEL ', id_municipio: 12 },
		{ id: 1046, parroquia: 'LA SIERRITA ', id_municipio: 12 },
		{ id: 1047, parroquia: 'LAS PARCELAS ', id_municipio: 12 },
		{ id: 1048, parroquia: 'LUIS DE VICENTE ', id_municipio: 12 },
		{ id: 1049, parroquia: 'MONSEÑOR', id_municipio: 23 },
		{ id: 1050, parroquia: 'RICAURTE ', id_municipio: 12 },
		{ id: 1051, parroquia: 'TAMARE ', id_municipio: 12 },
		{ id: 1052, parroquia: 'ANTONIO BORJAS ROMERO ', id_municipio: 13 },
		{ id: 1053, parroquia: 'BOLIVAR ', id_municipio: 13 },
		{ id: 1054, parroquia: 'CACIQUE MARA ', id_municipio: 13 },
		{ id: 1055, parroquia: 'CARACCIOLO PARRA PEREZ ', id_municipio: 13 },
		{ id: 1056, parroquia: 'CECILIO ACOSTA ', id_municipio: 13 },
		{ id: 1057, parroquia: 'CRISTO DE ARANZA ', id_municipio: 13 },
		{ id: 1058, parroquia: 'COQUIVACOA ', id_municipio: 13 },
		{ id: 1059, parroquia: 'CHIQUINQUIRA ', id_municipio: 13 },
		{ id: 1060, parroquia: 'FRANCISCO EUGENIO BUSTAMANTE ', id_municipio: 13 },
		{ id: 1061, parroquia: 'IDELFONSO VASQUEZ ', id_municipio: 13 },
		{ id: 1062, parroquia: 'JUANA DE AVILA ', id_municipio: 13 },
		{ id: 1063, parroquia: 'LUIS HURTADO HIGUERA ', id_municipio: 13 },
		{ id: 1064, parroquia: 'MANUEL DAGNINO ', id_municipio: 13 },
		{ id: 1065, parroquia: 'OLEGARIO VILLALOBOS ', id_municipio: 13 },
		{ id: 1066, parroquia: 'RAUL LEONI ', id_municipio: 13 },
		{ id: 1067, parroquia: 'SANTA LUCIA ', id_municipio: 13 },
		{ id: 1068, parroquia: 'VENANCIO PULGAR ', id_municipio: 13 },
		{ id: 1069, parroquia: 'SAN ISIDRO ', id_municipio: 13 },
		{ id: 1070, parroquia: 'ALTAGRACIA ', id_municipio: 14 },
		{ id: 1071, parroquia: 'ANA MARIA CAMPOS ', id_municipio: 14 },
		{ id: 1072, parroquia: 'FARIA ', id_municipio: 14 },
		{ id: 1073, parroquia: 'SAN ANTONIO ', id_municipio: 14 },
		{ id: 1074, parroquia: 'SAN JOSE ', id_municipio: 14 },
		{ id: 1075, parroquia: 'SINAMAICA ', id_municipio: 15 },
		{ id: 1076, parroquia: 'ALTA GUAJIRA ', id_municipio: 15 },
		{ id: 1077, parroquia: 'ELIAS SANCHEZ RUBIO ', id_municipio: 15 },
		{ id: 1078, parroquia: 'GUAJIRA ', id_municipio: 15 },
		{ id: 1079, parroquia: 'EL ROSARIO ', id_municipio: 16 },
		{ id: 1080, parroquia: 'DONALDO GARCIA ', id_municipio: 16 },
		{ id: 1081, parroquia: 'SIXTO ZAMBRANO ', id_municipio: 16 },
		{ id: 1082, parroquia: 'SAN FRANCISCO ', id_municipio: 17 },
		{ id: 1083, parroquia: 'EL BAJO ', id_municipio: 17 },
		{ id: 1084, parroquia: 'DOMITILA FLORES ', id_municipio: 17 },
		{ id: 1085, parroquia: 'ELIAS SANCHEZ RUBIO ', id_municipio: 17 },
		{ id: 1086, parroquia: 'LOS CORTIJOS ', id_municipio: 17 },
		{ id: 1087, parroquia: 'MARCIAL HERNANDEZ ', id_municipio: 17 },
		{ id: 1088, parroquia: 'SANTA RITA ', id_municipio: 18 },
		{ id: 1089, parroquia: 'EL MENE ', id_municipio: 18 },
		{ id: 1090, parroquia: 'JOSE CENOVIO URRIBARRI ', id_municipio: 18 },
		{ id: 1091, parroquia: 'PEDRO LUCAS URRIBARRI ', id_municipio: 18 },
		{ id: 1092, parroquia: 'MANUEL MANRIQUE ', id_municipio: 19 },
		{ id: 1093, parroquia: 'RAFAEL MARIA BARALT ', id_municipio: 19 },
		{ id: 1094, parroquia: 'RAFAEL URDANETA ', id_municipio: 19 },
		{ id: 1095, parroquia: 'BOBURES ', id_municipio: 20 },
		{ id: 1096, parroquia: 'EL BATEY ', id_municipio: 20 },
		{ id: 1097, parroquia: 'GIBRALTAR ', id_municipio: 20 },
		{ id: 1098, parroquia: 'HERAS ', id_municipio: 20 },
		{ id: 1099, parroquia: 'MONS. ARTURO CELESTINO A ', id_municipio: 20 },
		{ id: 1100, parroquia: 'ROMULO GALLEGOS ', id_municipio: 20 },
		{ id: 1101, parroquia: 'LA VICTORIA ', id_municipio: 21 },
		{ id: 1102, parroquia: 'RAFAEL URDANETA ', id_municipio: 21 },
		{ id: 1103, parroquia: 'RAUL CUENCA ', id_municipio: 21 },
		{ id: 1104, parroquia: 'CARABALLEDA ', id_municipio: 335 },
		{ id: 1105, parroquia: 'CARAYACA ', id_municipio: 1 },
		{ id: 1106, parroquia: 'CARUAO ', id_municipio: 335 },
		{ id: 1107, parroquia: 'CATIA LA MAR ', id_municipio: 335 },
		{ id: 1108, parroquia: 'EL JUNKO ', id_municipio: 335 },
		{ id: 1109, parroquia: 'LA GUAIRA ', id_municipio: 1 },
		{ id: 1110, parroquia: 'MACUTO ', id_municipio: 1 },
		{ id: 1111, parroquia: 'MAIQUETIA ', id_municipio: 1 },
		{ id: 1112, parroquia: 'NAIGUATA ', id_municipio: 1 },
		{ id: 1113, parroquia: 'RAUL LEONI ', id_municipio: 1 },
		{ id: 1114, parroquia: 'CARLOS SOUBLETTE ', id_municipio: 1 },
		{ id: 1115, parroquia: 'GRAN ROQUE ', id_municipio: 1 },
		{ id: 1116, parroquia: 'TESTIGOS, LOS ', id_municipio: 1 },
		{ id: 1117, parroquia: 'CHIMANAS ', id_municipio: 1 },
		{ id: 1118, parroquia: 'FERNANDO GIRON TOVAR ', id_municipio: 3 },
	];

	//
	let i: number = (data.length - 1) / 5 + 1;
	const rangos: any[] = [
		{ init: 0, end: Math.round(i) },
		{ init: Math.round(i), end: Math.round(i * 2) },
		{ init: Math.round(i * 2), end: Math.round(i * 3) },
		{ init: Math.round(i * 3), end: Math.round(i * 4) },
		{ init: Math.round(i * 4), end: Math.round(data.length) },
	];

	for (let i = 0; i < rangos.length; i++) {
		const item = rangos[i];

		const { init, end } = item;
		const info: fm_parroquia[] = data.slice(init, end);
		const valid = await getRepository(fm_parroquia).find({ where: info });
		if (!valid.length) await getRepository(fm_parroquia).save(info);
	}
};

export default parroquia;
